//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegOnline.RegressionTest.Fixtures.API.RegistrationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.regonline.com/webservices/", ConfigurationName="RegistrationService.RegistrationServiceSoap")]
    public interface RegistrationServiceSoap {
        
        // CODEGEN: Generating message contract since message CheckRegistrationStatusRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://www.regonline.com/webservices/CheckRegistrationStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RegOnline.RegressionTest.Fixtures.API.RegistrationService.CheckRegistrationStatusResponse CheckRegistrationStatus(RegOnline.RegressionTest.Fixtures.API.RegistrationService.CheckRegistrationStatusRequest request);
        
        // CODEGEN: Generating message contract since message InitializeRegistrationSessionRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://www.regonline.com/webservices/InitializeRegistrationSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RegOnline.RegressionTest.Fixtures.API.RegistrationService.InitializeRegistrationSessionResponse InitializeRegistrationSession(RegOnline.RegressionTest.Fixtures.API.RegistrationService.InitializeRegistrationSessionRequest request);
        
        // CODEGEN: Generating message contract since message SetBibNumberRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://www.regonline.com/webservices/SetBibNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RegOnline.RegressionTest.Fixtures.API.RegistrationService.SetBibNumberResponse SetBibNumber(RegOnline.RegressionTest.Fixtures.API.RegistrationService.SetBibNumberRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.regonline.com/webservices/")]
    public partial class AuthenticationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.regonline.com/webservices/")]
    public partial class InitializeRegistrationSessionResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIdField;
        
        private int registrationIdField;
        
        private string uRLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("SessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int RegistrationId {
            get {
                return this.registrationIdField;
            }
            set {
                this.registrationIdField = value;
                this.RaisePropertyChanged("RegistrationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.regonline.com/webservices/")]
    public partial class RegOnlineResponseOfInitializeRegistrationSessionResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InitializeRegistrationSessionResponseType valueField;
        
        private ResponseStatus statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InitializeRegistrationSessionResponseType Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.regonline.com/webservices/")]
    public partial class ResponseStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string errorMessageField;
        
        private int errorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.regonline.com/webservices/2009/02/StandardPersonalInformation.Generate" +
        "d.xsd")]
    public partial class nameValueSet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.regonline.com/webservices/")]
    public partial class RegOnlineResponseOfInt32 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int valueField;
        
        private ResponseStatus statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckRegistrationStatus", WrapperNamespace="https://www.regonline.com/webservices/", IsWrapped=true)]
    public partial class CheckRegistrationStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.regonline.com/webservices/")]
        public RegOnline.RegressionTest.Fixtures.API.RegistrationService.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.regonline.com/webservices/", Order=0)]
        public int RegistrationID;
        
        public CheckRegistrationStatusRequest() {
        }
        
        public CheckRegistrationStatusRequest(RegOnline.RegressionTest.Fixtures.API.RegistrationService.AuthenticationHeader AuthenticationHeader, int RegistrationID) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.RegistrationID = RegistrationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckRegistrationStatusResponse", WrapperNamespace="https://www.regonline.com/webservices/", IsWrapped=true)]
    public partial class CheckRegistrationStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.regonline.com/webservices/", Order=0)]
        public RegOnline.RegressionTest.Fixtures.API.RegistrationService.RegOnlineResponseOfInt32 CheckRegistrationStatusResult;
        
        public CheckRegistrationStatusResponse() {
        }
        
        public CheckRegistrationStatusResponse(RegOnline.RegressionTest.Fixtures.API.RegistrationService.RegOnlineResponseOfInt32 CheckRegistrationStatusResult) {
            this.CheckRegistrationStatusResult = CheckRegistrationStatusResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.regonline.com/webservices/2009/02/StandardPersonalInformation.Generate" +
        "d.xsd")]
    public partial class personalInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailAddressField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string memberIdField;
        
        private System.Nullable<System.DateTime> birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private string genderField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string postalCodeField;
        
        private string countryField;
        
        private string homePhoneField;
        
        private string workPhoneField;
        
        private string mobilePhoneField;
        
        private nameValueSet[] additionalDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("emailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
                this.RaisePropertyChanged("middleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string memberId {
            get {
                return this.memberIdField;
            }
            set {
                this.memberIdField = value;
                this.RaisePropertyChanged("memberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("birthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
                this.RaisePropertyChanged("birthDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("postalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string homePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
                this.RaisePropertyChanged("homePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string workPhone {
            get {
                return this.workPhoneField;
            }
            set {
                this.workPhoneField = value;
                this.RaisePropertyChanged("workPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string mobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
                this.RaisePropertyChanged("mobilePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute("additionalDetails", IsNullable=false)]
        public nameValueSet[] additionalDetails {
            get {
                return this.additionalDetailsField;
            }
            set {
                this.additionalDetailsField = value;
                this.RaisePropertyChanged("additionalDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitializeRegistrationSession", WrapperNamespace="https://www.regonline.com/webservices/", IsWrapped=true)]
    public partial class InitializeRegistrationSessionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.regonline.com/webservices/")]
        public RegOnline.RegressionTest.Fixtures.API.RegistrationService.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.regonline.com/webservices/", Order=0)]
        public int eventID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.regonline.com/webservices/", Order=1)]
        public decimal amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.regonline.com/webservices/2009/02/StandardPersonalInformation.Generate" +
            "d.xsd", Order=2)]
        public RegOnline.RegressionTest.Fixtures.API.RegistrationService.personalInfo personalInfo;
        
        public InitializeRegistrationSessionRequest() {
        }
        
        public InitializeRegistrationSessionRequest(RegOnline.RegressionTest.Fixtures.API.RegistrationService.AuthenticationHeader AuthenticationHeader, int eventID, decimal amount, RegOnline.RegressionTest.Fixtures.API.RegistrationService.personalInfo personalInfo) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.eventID = eventID;
            this.amount = amount;
            this.personalInfo = personalInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitializeRegistrationSessionResponse", WrapperNamespace="https://www.regonline.com/webservices/", IsWrapped=true)]
    public partial class InitializeRegistrationSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.regonline.com/webservices/", Order=0)]
        public RegOnline.RegressionTest.Fixtures.API.RegistrationService.RegOnlineResponseOfInitializeRegistrationSessionResponseType InitializeRegistrationSessionResult;
        
        public InitializeRegistrationSessionResponse() {
        }
        
        public InitializeRegistrationSessionResponse(RegOnline.RegressionTest.Fixtures.API.RegistrationService.RegOnlineResponseOfInitializeRegistrationSessionResponseType InitializeRegistrationSessionResult) {
            this.InitializeRegistrationSessionResult = InitializeRegistrationSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetBibNumber", WrapperNamespace="https://www.regonline.com/webservices/", IsWrapped=true)]
    public partial class SetBibNumberRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.regonline.com/webservices/")]
        public RegOnline.RegressionTest.Fixtures.API.RegistrationService.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.regonline.com/webservices/", Order=0)]
        public int eventId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.regonline.com/webservices/", Order=1)]
        public int registerId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.regonline.com/webservices/", Order=2)]
        public int regTypeId;
        
        public SetBibNumberRequest() {
        }
        
        public SetBibNumberRequest(RegOnline.RegressionTest.Fixtures.API.RegistrationService.AuthenticationHeader AuthenticationHeader, int eventId, int registerId, int regTypeId) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.eventId = eventId;
            this.registerId = registerId;
            this.regTypeId = regTypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetBibNumberResponse", WrapperNamespace="https://www.regonline.com/webservices/", IsWrapped=true)]
    public partial class SetBibNumberResponse {
        
        public SetBibNumberResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistrationServiceSoapChannel : RegOnline.RegressionTest.Fixtures.API.RegistrationService.RegistrationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationServiceSoapClient : System.ServiceModel.ClientBase<RegOnline.RegressionTest.Fixtures.API.RegistrationService.RegistrationServiceSoap>, RegOnline.RegressionTest.Fixtures.API.RegistrationService.RegistrationServiceSoap {
        
        public RegistrationServiceSoapClient() {
        }
        
        public RegistrationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RegOnline.RegressionTest.Fixtures.API.RegistrationService.CheckRegistrationStatusResponse RegOnline.RegressionTest.Fixtures.API.RegistrationService.RegistrationServiceSoap.CheckRegistrationStatus(RegOnline.RegressionTest.Fixtures.API.RegistrationService.CheckRegistrationStatusRequest request) {
            return base.Channel.CheckRegistrationStatus(request);
        }
        
        public RegOnline.RegressionTest.Fixtures.API.RegistrationService.RegOnlineResponseOfInt32 CheckRegistrationStatus(RegOnline.RegressionTest.Fixtures.API.RegistrationService.AuthenticationHeader AuthenticationHeader, int RegistrationID) {
            RegOnline.RegressionTest.Fixtures.API.RegistrationService.CheckRegistrationStatusRequest inValue = new RegOnline.RegressionTest.Fixtures.API.RegistrationService.CheckRegistrationStatusRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.RegistrationID = RegistrationID;
            RegOnline.RegressionTest.Fixtures.API.RegistrationService.CheckRegistrationStatusResponse retVal = ((RegOnline.RegressionTest.Fixtures.API.RegistrationService.RegistrationServiceSoap)(this)).CheckRegistrationStatus(inValue);
            return retVal.CheckRegistrationStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RegOnline.RegressionTest.Fixtures.API.RegistrationService.InitializeRegistrationSessionResponse RegOnline.RegressionTest.Fixtures.API.RegistrationService.RegistrationServiceSoap.InitializeRegistrationSession(RegOnline.RegressionTest.Fixtures.API.RegistrationService.InitializeRegistrationSessionRequest request) {
            return base.Channel.InitializeRegistrationSession(request);
        }
        
        public RegOnline.RegressionTest.Fixtures.API.RegistrationService.RegOnlineResponseOfInitializeRegistrationSessionResponseType InitializeRegistrationSession(RegOnline.RegressionTest.Fixtures.API.RegistrationService.AuthenticationHeader AuthenticationHeader, int eventID, decimal amount, RegOnline.RegressionTest.Fixtures.API.RegistrationService.personalInfo personalInfo) {
            RegOnline.RegressionTest.Fixtures.API.RegistrationService.InitializeRegistrationSessionRequest inValue = new RegOnline.RegressionTest.Fixtures.API.RegistrationService.InitializeRegistrationSessionRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.eventID = eventID;
            inValue.amount = amount;
            inValue.personalInfo = personalInfo;
            RegOnline.RegressionTest.Fixtures.API.RegistrationService.InitializeRegistrationSessionResponse retVal = ((RegOnline.RegressionTest.Fixtures.API.RegistrationService.RegistrationServiceSoap)(this)).InitializeRegistrationSession(inValue);
            return retVal.InitializeRegistrationSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RegOnline.RegressionTest.Fixtures.API.RegistrationService.SetBibNumberResponse RegOnline.RegressionTest.Fixtures.API.RegistrationService.RegistrationServiceSoap.SetBibNumber(RegOnline.RegressionTest.Fixtures.API.RegistrationService.SetBibNumberRequest request) {
            return base.Channel.SetBibNumber(request);
        }
        
        public void SetBibNumber(RegOnline.RegressionTest.Fixtures.API.RegistrationService.AuthenticationHeader AuthenticationHeader, int eventId, int registerId, int regTypeId) {
            RegOnline.RegressionTest.Fixtures.API.RegistrationService.SetBibNumberRequest inValue = new RegOnline.RegressionTest.Fixtures.API.RegistrationService.SetBibNumberRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.eventId = eventId;
            inValue.registerId = registerId;
            inValue.regTypeId = regTypeId;
            RegOnline.RegressionTest.Fixtures.API.RegistrationService.SetBibNumberResponse retVal = ((RegOnline.RegressionTest.Fixtures.API.RegistrationService.RegistrationServiceSoap)(this)).SetBibNumber(inValue);
        }
    }
}
