//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegOnline.RegressionTest.Fixtures.API.RegOnlineRetrieveAllRegsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.regonline.com/webservices/", ConfigurationName="RegOnlineRetrieveAllRegsService.RetrieveAllRegistrationsManagerSoap")]
    public interface RetrieveAllRegistrationsManagerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.regonline.com/webservices/RetrieveAllRegistrations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RetrieveAllRegistrations(string customerUserName, string customerPassword, int eventID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RetrieveAllRegistrationsManagerSoapChannel : RegOnline.RegressionTest.Fixtures.API.RegOnlineRetrieveAllRegsService.RetrieveAllRegistrationsManagerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveAllRegistrationsManagerSoapClient : System.ServiceModel.ClientBase<RegOnline.RegressionTest.Fixtures.API.RegOnlineRetrieveAllRegsService.RetrieveAllRegistrationsManagerSoap>, RegOnline.RegressionTest.Fixtures.API.RegOnlineRetrieveAllRegsService.RetrieveAllRegistrationsManagerSoap {
        
        public RetrieveAllRegistrationsManagerSoapClient() {
        }
        
        public RetrieveAllRegistrationsManagerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetrieveAllRegistrationsManagerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetrieveAllRegistrationsManagerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetrieveAllRegistrationsManagerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RetrieveAllRegistrations(string customerUserName, string customerPassword, int eventID) {
            return base.Channel.RetrieveAllRegistrations(customerUserName, customerPassword, eventID);
        }
    }
}
