//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegOnline.RegressionTest.NUnitAddin.CIPReporter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="RegressionTestService", ConfigurationName="CIPReporter.RegressionTestServiceSoap")]
    public interface RegressionTestServiceSoap {
        
        // CODEGEN: Generating message contract since element name testName from namespace RegressionTestService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="RegressionTestService/InsertTestResult", ReplyAction="*")]
        RegOnline.RegressionTest.NUnitAddin.CIPReporter.InsertTestResultResponse InsertTestResult(RegOnline.RegressionTest.NUnitAddin.CIPReporter.InsertTestResultRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertTestResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertTestResult", Namespace="RegressionTestService", Order=0)]
        public RegOnline.RegressionTest.NUnitAddin.CIPReporter.InsertTestResultRequestBody Body;
        
        public InsertTestResultRequest() {
        }
        
        public InsertTestResultRequest(RegOnline.RegressionTest.NUnitAddin.CIPReporter.InsertTestResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="RegressionTestService")]
    public partial class InsertTestResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string testName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string runBy;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool success;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string resultDescription;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double runTime;
        
        public InsertTestResultRequestBody() {
        }
        
        public InsertTestResultRequestBody(string testName, string runBy, bool success, string resultDescription, double runTime) {
            this.testName = testName;
            this.runBy = runBy;
            this.success = success;
            this.resultDescription = resultDescription;
            this.runTime = runTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertTestResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertTestResultResponse", Namespace="RegressionTestService", Order=0)]
        public RegOnline.RegressionTest.NUnitAddin.CIPReporter.InsertTestResultResponseBody Body;
        
        public InsertTestResultResponse() {
        }
        
        public InsertTestResultResponse(RegOnline.RegressionTest.NUnitAddin.CIPReporter.InsertTestResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertTestResultResponseBody {
        
        public InsertTestResultResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegressionTestServiceSoapChannel : RegOnline.RegressionTest.NUnitAddin.CIPReporter.RegressionTestServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegressionTestServiceSoapClient : System.ServiceModel.ClientBase<RegOnline.RegressionTest.NUnitAddin.CIPReporter.RegressionTestServiceSoap>, RegOnline.RegressionTest.NUnitAddin.CIPReporter.RegressionTestServiceSoap {
        
        public RegressionTestServiceSoapClient() {
        }
        
        public RegressionTestServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegressionTestServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegressionTestServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegressionTestServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RegOnline.RegressionTest.NUnitAddin.CIPReporter.InsertTestResultResponse RegOnline.RegressionTest.NUnitAddin.CIPReporter.RegressionTestServiceSoap.InsertTestResult(RegOnline.RegressionTest.NUnitAddin.CIPReporter.InsertTestResultRequest request) {
            return base.Channel.InsertTestResult(request);
        }
        
        public void InsertTestResult(string testName, string runBy, bool success, string resultDescription, double runTime) {
            RegOnline.RegressionTest.NUnitAddin.CIPReporter.InsertTestResultRequest inValue = new RegOnline.RegressionTest.NUnitAddin.CIPReporter.InsertTestResultRequest();
            inValue.Body = new RegOnline.RegressionTest.NUnitAddin.CIPReporter.InsertTestResultRequestBody();
            inValue.Body.testName = testName;
            inValue.Body.runBy = runBy;
            inValue.Body.success = success;
            inValue.Body.resultDescription = resultDescription;
            inValue.Body.runTime = runTime;
            RegOnline.RegressionTest.NUnitAddin.CIPReporter.InsertTestResultResponse retVal = ((RegOnline.RegressionTest.NUnitAddin.CIPReporter.RegressionTestServiceSoap)(this)).InsertTestResult(inValue);
        }
    }
}
