//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegOnline.RegressionTest.Fixtures.API.RegOnlineReportsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Regonline Web ServicesSoap", Namespace="http://www.regonline.com/", ConfigurationName="RegOnlineReportsService.RegonlineWebServicesSoap")]
    public interface RegonlineWebServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.regonline.com/getReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getReport(string login, string pass, int customerID, int reportID, int eventID, string startDate, string endDate, bool bAddDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.regonline.com/getNonCompressedReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getNonCompressedReport(string login, string pass, int customerID, int reportID, int eventID, string startDate, string endDate, bool bAddDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegonlineWebServicesSoapChannel : RegOnline.RegressionTest.Fixtures.API.RegOnlineReportsService.RegonlineWebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegonlineWebServicesSoapClient : System.ServiceModel.ClientBase<RegOnline.RegressionTest.Fixtures.API.RegOnlineReportsService.RegonlineWebServicesSoap>, RegOnline.RegressionTest.Fixtures.API.RegOnlineReportsService.RegonlineWebServicesSoap {
        
        public RegonlineWebServicesSoapClient() {
        }
        
        public RegonlineWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegonlineWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegonlineWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegonlineWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getReport(string login, string pass, int customerID, int reportID, int eventID, string startDate, string endDate, bool bAddDate) {
            return base.Channel.getReport(login, pass, customerID, reportID, eventID, startDate, endDate, bAddDate);
        }
        
        public string getNonCompressedReport(string login, string pass, int customerID, int reportID, int eventID, string startDate, string endDate, bool bAddDate) {
            return base.Channel.getNonCompressedReport(login, pass, customerID, reportID, eventID, startDate, endDate, bAddDate);
        }
    }
}
