#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegOnline.RegressionTest.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ROMaster")]
	public partial class ROMasterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomerInvoiceItem(CustomerInvoiceItem instance);
    partial void UpdateCustomerInvoiceItem(CustomerInvoiceItem instance);
    partial void DeleteCustomerInvoiceItem(CustomerInvoiceItem instance);
    partial void InsertCustomerInvoice(CustomerInvoice instance);
    partial void UpdateCustomerInvoice(CustomerInvoice instance);
    partial void DeleteCustomerInvoice(CustomerInvoice instance);
    partial void InsertCustomerTransaction(CustomerTransaction instance);
    partial void UpdateCustomerTransaction(CustomerTransaction instance);
    partial void DeleteCustomerTransaction(CustomerTransaction instance);
    partial void InsertSession(Session instance);
    partial void UpdateSession(Session instance);
    partial void DeleteSession(Session instance);
    partial void InsertShortcut(Shortcut instance);
    partial void UpdateShortcut(Shortcut instance);
    partial void DeleteShortcut(Shortcut instance);
    #endregion

		public ROMasterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ROMasterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ROMasterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ROMasterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CustomerInvoiceItem> CustomerInvoiceItems
		{
			get
			{
				return this.GetTable<CustomerInvoiceItem>();
			}
		}
		
		public System.Data.Linq.Table<CustomerInvoice> CustomerInvoices
		{
			get
			{
				return this.GetTable<CustomerInvoice>();
			}
		}
		
		public System.Data.Linq.Table<CustomerTransaction> CustomerTransactions
		{
			get
			{
				return this.GetTable<CustomerTransaction>();
			}
		}
		
		public System.Data.Linq.Table<Session> Sessions
		{
			get
			{
				return this.GetTable<Session>();
			}
		}
		
		public System.Data.Linq.Table<Shortcut> Shortcuts
		{
			get
			{
				return this.GetTable<Shortcut>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerInvoiceItems")]
	public partial class CustomerInvoiceItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _InvoiceId;
		
		private int _ItemId;
		
		private int _EventId;
		
		private System.Nullable<decimal> _CCAmount;
		
		private System.Nullable<decimal> _CCCost;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<int> _RegCount;
		
		private string _INVOICE_COMMENT;
		
		private EntityRef<CustomerInvoice> _CustomerInvoice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInvoiceIdChanging(int value);
    partial void OnInvoiceIdChanged();
    partial void OnItemIdChanging(int value);
    partial void OnItemIdChanged();
    partial void OnEventIdChanging(int value);
    partial void OnEventIdChanged();
    partial void OnCCAmountChanging(System.Nullable<decimal> value);
    partial void OnCCAmountChanged();
    partial void OnCCCostChanging(System.Nullable<decimal> value);
    partial void OnCCCostChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OnRegCountChanging(System.Nullable<int> value);
    partial void OnRegCountChanged();
    partial void OnINVOICE_COMMENTChanging(string value);
    partial void OnINVOICE_COMMENTChanged();
    #endregion
		
		public CustomerInvoiceItem()
		{
			this._CustomerInvoice = default(EntityRef<CustomerInvoice>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int InvoiceId
		{
			get
			{
				return this._InvoiceId;
			}
			set
			{
				if ((this._InvoiceId != value))
				{
					if (this._CustomerInvoice.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnInvoiceIdChanging(value);
					this.SendPropertyChanging();
					this._InvoiceId = value;
					this.SendPropertyChanged("InvoiceId");
					this.OnInvoiceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ItemId
		{
			get
			{
				return this._ItemId;
			}
			set
			{
				if ((this._ItemId != value))
				{
					this.OnItemIdChanging(value);
					this.SendPropertyChanging();
					this._ItemId = value;
					this.SendPropertyChanged("ItemId");
					this.OnItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				if ((this._EventId != value))
				{
					this.OnEventIdChanging(value);
					this.SendPropertyChanging();
					this._EventId = value;
					this.SendPropertyChanged("EventId");
					this.OnEventIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCAmount", DbType="Money")]
		public System.Nullable<decimal> CCAmount
		{
			get
			{
				return this._CCAmount;
			}
			set
			{
				if ((this._CCAmount != value))
				{
					this.OnCCAmountChanging(value);
					this.SendPropertyChanging();
					this._CCAmount = value;
					this.SendPropertyChanged("CCAmount");
					this.OnCCAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCost", DbType="Money")]
		public System.Nullable<decimal> CCCost
		{
			get
			{
				return this._CCCost;
			}
			set
			{
				if ((this._CCCost != value))
				{
					this.OnCCCostChanging(value);
					this.SendPropertyChanging();
					this._CCCost = value;
					this.SendPropertyChanged("CCCost");
					this.OnCCCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegCount", DbType="Int")]
		public System.Nullable<int> RegCount
		{
			get
			{
				return this._RegCount;
			}
			set
			{
				if ((this._RegCount != value))
				{
					this.OnRegCountChanging(value);
					this.SendPropertyChanging();
					this._RegCount = value;
					this.SendPropertyChanged("RegCount");
					this.OnRegCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INVOICE_COMMENT", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string INVOICE_COMMENT
		{
			get
			{
				return this._INVOICE_COMMENT;
			}
			set
			{
				if ((this._INVOICE_COMMENT != value))
				{
					this.OnINVOICE_COMMENTChanging(value);
					this.SendPropertyChanging();
					this._INVOICE_COMMENT = value;
					this.SendPropertyChanged("INVOICE_COMMENT");
					this.OnINVOICE_COMMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CustomerInvoice_CustomerInvoiceItem", Storage="_CustomerInvoice", ThisKey="InvoiceId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public CustomerInvoice CustomerInvoice
		{
			get
			{
				return this._CustomerInvoice.Entity;
			}
			set
			{
				CustomerInvoice previousValue = this._CustomerInvoice.Entity;
				if (((previousValue != value) 
							|| (this._CustomerInvoice.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CustomerInvoice.Entity = null;
						previousValue.CustomerInvoiceItems.Remove(this);
					}
					this._CustomerInvoice.Entity = value;
					if ((value != null))
					{
						value.CustomerInvoiceItems.Add(this);
						this._InvoiceId = value.Id;
					}
					else
					{
						this._InvoiceId = default(int);
					}
					this.SendPropertyChanged("CustomerInvoice");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerInvoices")]
	public partial class CustomerInvoice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private byte _TypeId;
		
		private int _CustomerId;
		
		private System.Nullable<System.DateTime> _InvoiceDate;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private string _Bill_Company;
		
		private string _Bill_First_Name;
		
		private string _Bill_Last_Name;
		
		private string _Bill_Address_1;
		
		private string _Bill_Address_2;
		
		private string _Bill_City;
		
		private string _Bill_Region;
		
		private string _Bill_Country;
		
		private string _Bill_Postal_Code;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _Email_Name;
		
		private System.Nullable<int> _Payment_Method_Id;
		
		private string _CC_Number;
		
		private System.Nullable<System.DateTime> _CC_Expiration_Date;
		
		private string _CC_Name_If_Different;
		
		private System.Nullable<float> _Fee_CC_Visa_Pct;
		
		private System.Nullable<decimal> _Fee_CC_Visa_Flat;
		
		private System.Nullable<float> _Fee_CC_MC_PCT;
		
		private System.Nullable<decimal> _Fee_CC_MC_Flat;
		
		private System.Nullable<float> _Fee_CC_Amex_Pct;
		
		private System.Nullable<decimal> _Fee_CC_Amex_Flat;
		
		private System.Nullable<float> _Fee_CC_Discover_Pct;
		
		private System.Nullable<decimal> _Fee_CC_Discover_Flat;
		
		private System.Nullable<float> _Fee_CC_Diners_Pct;
		
		private System.Nullable<decimal> _Fee_CC_Diners_Flat;
		
		private System.Nullable<decimal> _Fee_CC_Minimum;
		
		private System.Nullable<decimal> _Fee_Event_Setup;
		
		private System.Nullable<decimal> _Fee_Waitlist_Setup;
		
		private System.Nullable<decimal> _Fee_1;
		
		private System.Nullable<decimal> _Fee_2;
		
		private System.Nullable<decimal> _Fee_Survey;
		
		private System.Nullable<decimal> _Fee_One_Time;
		
		private System.Nullable<bool> _Fee_Apply_Flat;
		
		private System.Nullable<decimal> _Fee_Reminder;
		
		private System.Nullable<decimal> _Fee_Email;
		
		private System.Nullable<bool> _Fee_Email_Flat;
		
		private System.Nullable<bool> _Fee_Charge_For_Parent;
		
		private System.Nullable<decimal> _Fee_Chargeback_Fee;
		
		private string _BaseCurrencyCode;
		
		private System.Nullable<bool> _Fee_PayWithCreditCard;
		
		private System.Nullable<System.DateTime> _Add_Date;
		
		private string _Add_By;
		
		private System.Nullable<System.DateTime> _Mod_Date;
		
		private string _Mod_By;
		
		private System.Nullable<int> _EventBillingId;
		
		private System.Nullable<bool> _ukAccount;
		
		private System.Nullable<bool> _collectVatTax;
		
		private string _VatTaxId;
		
		private System.Nullable<System.DateTime> _InvoiceEmailDate;
		
		private EntitySet<CustomerInvoiceItem> _CustomerInvoiceItems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTypeIdChanging(byte value);
    partial void OnTypeIdChanged();
    partial void OnCustomerIdChanging(int value);
    partial void OnCustomerIdChanged();
    partial void OnInvoiceDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInvoiceDateChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    partial void OnBill_CompanyChanging(string value);
    partial void OnBill_CompanyChanged();
    partial void OnBill_First_NameChanging(string value);
    partial void OnBill_First_NameChanged();
    partial void OnBill_Last_NameChanging(string value);
    partial void OnBill_Last_NameChanged();
    partial void OnBill_Address_1Changing(string value);
    partial void OnBill_Address_1Changed();
    partial void OnBill_Address_2Changing(string value);
    partial void OnBill_Address_2Changed();
    partial void OnBill_CityChanging(string value);
    partial void OnBill_CityChanged();
    partial void OnBill_RegionChanging(string value);
    partial void OnBill_RegionChanged();
    partial void OnBill_CountryChanging(string value);
    partial void OnBill_CountryChanged();
    partial void OnBill_Postal_CodeChanging(string value);
    partial void OnBill_Postal_CodeChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnEmail_NameChanging(string value);
    partial void OnEmail_NameChanged();
    partial void OnPayment_Method_IdChanging(System.Nullable<int> value);
    partial void OnPayment_Method_IdChanged();
    partial void OnCC_NumberChanging(string value);
    partial void OnCC_NumberChanged();
    partial void OnCC_Expiration_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnCC_Expiration_DateChanged();
    partial void OnCC_Name_If_DifferentChanging(string value);
    partial void OnCC_Name_If_DifferentChanged();
    partial void OnFee_CC_Visa_PctChanging(System.Nullable<float> value);
    partial void OnFee_CC_Visa_PctChanged();
    partial void OnFee_CC_Visa_FlatChanging(System.Nullable<decimal> value);
    partial void OnFee_CC_Visa_FlatChanged();
    partial void OnFee_CC_MC_PCTChanging(System.Nullable<float> value);
    partial void OnFee_CC_MC_PCTChanged();
    partial void OnFee_CC_MC_FlatChanging(System.Nullable<decimal> value);
    partial void OnFee_CC_MC_FlatChanged();
    partial void OnFee_CC_Amex_PctChanging(System.Nullable<float> value);
    partial void OnFee_CC_Amex_PctChanged();
    partial void OnFee_CC_Amex_FlatChanging(System.Nullable<decimal> value);
    partial void OnFee_CC_Amex_FlatChanged();
    partial void OnFee_CC_Discover_PctChanging(System.Nullable<float> value);
    partial void OnFee_CC_Discover_PctChanged();
    partial void OnFee_CC_Discover_FlatChanging(System.Nullable<decimal> value);
    partial void OnFee_CC_Discover_FlatChanged();
    partial void OnFee_CC_Diners_PctChanging(System.Nullable<float> value);
    partial void OnFee_CC_Diners_PctChanged();
    partial void OnFee_CC_Diners_FlatChanging(System.Nullable<decimal> value);
    partial void OnFee_CC_Diners_FlatChanged();
    partial void OnFee_CC_MinimumChanging(System.Nullable<decimal> value);
    partial void OnFee_CC_MinimumChanged();
    partial void OnFee_Event_SetupChanging(System.Nullable<decimal> value);
    partial void OnFee_Event_SetupChanged();
    partial void OnFee_Waitlist_SetupChanging(System.Nullable<decimal> value);
    partial void OnFee_Waitlist_SetupChanged();
    partial void OnFee_1Changing(System.Nullable<decimal> value);
    partial void OnFee_1Changed();
    partial void OnFee_2Changing(System.Nullable<decimal> value);
    partial void OnFee_2Changed();
    partial void OnFee_SurveyChanging(System.Nullable<decimal> value);
    partial void OnFee_SurveyChanged();
    partial void OnFee_One_TimeChanging(System.Nullable<decimal> value);
    partial void OnFee_One_TimeChanged();
    partial void OnFee_Apply_FlatChanging(System.Nullable<bool> value);
    partial void OnFee_Apply_FlatChanged();
    partial void OnFee_ReminderChanging(System.Nullable<decimal> value);
    partial void OnFee_ReminderChanged();
    partial void OnFee_EmailChanging(System.Nullable<decimal> value);
    partial void OnFee_EmailChanged();
    partial void OnFee_Email_FlatChanging(System.Nullable<bool> value);
    partial void OnFee_Email_FlatChanged();
    partial void OnFee_Charge_For_ParentChanging(System.Nullable<bool> value);
    partial void OnFee_Charge_For_ParentChanged();
    partial void OnFee_Chargeback_FeeChanging(System.Nullable<decimal> value);
    partial void OnFee_Chargeback_FeeChanged();
    partial void OnBaseCurrencyCodeChanging(string value);
    partial void OnBaseCurrencyCodeChanged();
    partial void OnFee_PayWithCreditCardChanging(System.Nullable<bool> value);
    partial void OnFee_PayWithCreditCardChanged();
    partial void OnAdd_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnAdd_DateChanged();
    partial void OnAdd_ByChanging(string value);
    partial void OnAdd_ByChanged();
    partial void OnMod_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnMod_DateChanged();
    partial void OnMod_ByChanging(string value);
    partial void OnMod_ByChanged();
    partial void OnEventBillingIdChanging(System.Nullable<int> value);
    partial void OnEventBillingIdChanged();
    partial void OnukAccountChanging(System.Nullable<bool> value);
    partial void OnukAccountChanged();
    partial void OncollectVatTaxChanging(System.Nullable<bool> value);
    partial void OncollectVatTaxChanged();
    partial void OnVatTaxIdChanging(string value);
    partial void OnVatTaxIdChanged();
    partial void OnInvoiceEmailDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInvoiceEmailDateChanged();
    #endregion
		
		public CustomerInvoice()
		{
			this._CustomerInvoiceItems = new EntitySet<CustomerInvoiceItem>(new Action<CustomerInvoiceItem>(this.attach_CustomerInvoiceItems), new Action<CustomerInvoiceItem>(this.detach_CustomerInvoiceItems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeId", DbType="TinyInt NOT NULL")]
		public byte TypeId
		{
			get
			{
				return this._TypeId;
			}
			set
			{
				if ((this._TypeId != value))
				{
					this.OnTypeIdChanging(value);
					this.SendPropertyChanging();
					this._TypeId = value;
					this.SendPropertyChanged("TypeId");
					this.OnTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", DbType="Int NOT NULL")]
		public int CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> InvoiceDate
		{
			get
			{
				return this._InvoiceDate;
			}
			set
			{
				if ((this._InvoiceDate != value))
				{
					this.OnInvoiceDateChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDate = value;
					this.SendPropertyChanged("InvoiceDate");
					this.OnInvoiceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bill_Company", DbType="NVarChar(100)")]
		public string Bill_Company
		{
			get
			{
				return this._Bill_Company;
			}
			set
			{
				if ((this._Bill_Company != value))
				{
					this.OnBill_CompanyChanging(value);
					this.SendPropertyChanging();
					this._Bill_Company = value;
					this.SendPropertyChanged("Bill_Company");
					this.OnBill_CompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bill_First_Name", DbType="NVarChar(50)")]
		public string Bill_First_Name
		{
			get
			{
				return this._Bill_First_Name;
			}
			set
			{
				if ((this._Bill_First_Name != value))
				{
					this.OnBill_First_NameChanging(value);
					this.SendPropertyChanging();
					this._Bill_First_Name = value;
					this.SendPropertyChanged("Bill_First_Name");
					this.OnBill_First_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bill_Last_Name", DbType="NVarChar(50)")]
		public string Bill_Last_Name
		{
			get
			{
				return this._Bill_Last_Name;
			}
			set
			{
				if ((this._Bill_Last_Name != value))
				{
					this.OnBill_Last_NameChanging(value);
					this.SendPropertyChanging();
					this._Bill_Last_Name = value;
					this.SendPropertyChanged("Bill_Last_Name");
					this.OnBill_Last_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bill_Address_1", DbType="NVarChar(50)")]
		public string Bill_Address_1
		{
			get
			{
				return this._Bill_Address_1;
			}
			set
			{
				if ((this._Bill_Address_1 != value))
				{
					this.OnBill_Address_1Changing(value);
					this.SendPropertyChanging();
					this._Bill_Address_1 = value;
					this.SendPropertyChanged("Bill_Address_1");
					this.OnBill_Address_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bill_Address_2", DbType="NVarChar(50)")]
		public string Bill_Address_2
		{
			get
			{
				return this._Bill_Address_2;
			}
			set
			{
				if ((this._Bill_Address_2 != value))
				{
					this.OnBill_Address_2Changing(value);
					this.SendPropertyChanging();
					this._Bill_Address_2 = value;
					this.SendPropertyChanged("Bill_Address_2");
					this.OnBill_Address_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bill_City", DbType="NVarChar(50)")]
		public string Bill_City
		{
			get
			{
				return this._Bill_City;
			}
			set
			{
				if ((this._Bill_City != value))
				{
					this.OnBill_CityChanging(value);
					this.SendPropertyChanging();
					this._Bill_City = value;
					this.SendPropertyChanged("Bill_City");
					this.OnBill_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bill_Region", DbType="NVarChar(50)")]
		public string Bill_Region
		{
			get
			{
				return this._Bill_Region;
			}
			set
			{
				if ((this._Bill_Region != value))
				{
					this.OnBill_RegionChanging(value);
					this.SendPropertyChanging();
					this._Bill_Region = value;
					this.SendPropertyChanged("Bill_Region");
					this.OnBill_RegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bill_Country", DbType="NVarChar(50)")]
		public string Bill_Country
		{
			get
			{
				return this._Bill_Country;
			}
			set
			{
				if ((this._Bill_Country != value))
				{
					this.OnBill_CountryChanging(value);
					this.SendPropertyChanging();
					this._Bill_Country = value;
					this.SendPropertyChanged("Bill_Country");
					this.OnBill_CountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bill_Postal_Code", DbType="NVarChar(50)")]
		public string Bill_Postal_Code
		{
			get
			{
				return this._Bill_Postal_Code;
			}
			set
			{
				if ((this._Bill_Postal_Code != value))
				{
					this.OnBill_Postal_CodeChanging(value);
					this.SendPropertyChanging();
					this._Bill_Postal_Code = value;
					this.SendPropertyChanged("Bill_Postal_Code");
					this.OnBill_Postal_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(50)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_Name", DbType="NVarChar(255)")]
		public string Email_Name
		{
			get
			{
				return this._Email_Name;
			}
			set
			{
				if ((this._Email_Name != value))
				{
					this.OnEmail_NameChanging(value);
					this.SendPropertyChanging();
					this._Email_Name = value;
					this.SendPropertyChanged("Email_Name");
					this.OnEmail_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment_Method_Id", DbType="Int")]
		public System.Nullable<int> Payment_Method_Id
		{
			get
			{
				return this._Payment_Method_Id;
			}
			set
			{
				if ((this._Payment_Method_Id != value))
				{
					this.OnPayment_Method_IdChanging(value);
					this.SendPropertyChanging();
					this._Payment_Method_Id = value;
					this.SendPropertyChanged("Payment_Method_Id");
					this.OnPayment_Method_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_Number", DbType="VarChar(50)")]
		public string CC_Number
		{
			get
			{
				return this._CC_Number;
			}
			set
			{
				if ((this._CC_Number != value))
				{
					this.OnCC_NumberChanging(value);
					this.SendPropertyChanging();
					this._CC_Number = value;
					this.SendPropertyChanged("CC_Number");
					this.OnCC_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_Expiration_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> CC_Expiration_Date
		{
			get
			{
				return this._CC_Expiration_Date;
			}
			set
			{
				if ((this._CC_Expiration_Date != value))
				{
					this.OnCC_Expiration_DateChanging(value);
					this.SendPropertyChanging();
					this._CC_Expiration_Date = value;
					this.SendPropertyChanged("CC_Expiration_Date");
					this.OnCC_Expiration_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_Name_If_Different", DbType="NVarChar(50)")]
		public string CC_Name_If_Different
		{
			get
			{
				return this._CC_Name_If_Different;
			}
			set
			{
				if ((this._CC_Name_If_Different != value))
				{
					this.OnCC_Name_If_DifferentChanging(value);
					this.SendPropertyChanging();
					this._CC_Name_If_Different = value;
					this.SendPropertyChanged("CC_Name_If_Different");
					this.OnCC_Name_If_DifferentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_CC_Visa_Pct", DbType="Real")]
		public System.Nullable<float> Fee_CC_Visa_Pct
		{
			get
			{
				return this._Fee_CC_Visa_Pct;
			}
			set
			{
				if ((this._Fee_CC_Visa_Pct != value))
				{
					this.OnFee_CC_Visa_PctChanging(value);
					this.SendPropertyChanging();
					this._Fee_CC_Visa_Pct = value;
					this.SendPropertyChanged("Fee_CC_Visa_Pct");
					this.OnFee_CC_Visa_PctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_CC_Visa_Flat", DbType="Money")]
		public System.Nullable<decimal> Fee_CC_Visa_Flat
		{
			get
			{
				return this._Fee_CC_Visa_Flat;
			}
			set
			{
				if ((this._Fee_CC_Visa_Flat != value))
				{
					this.OnFee_CC_Visa_FlatChanging(value);
					this.SendPropertyChanging();
					this._Fee_CC_Visa_Flat = value;
					this.SendPropertyChanged("Fee_CC_Visa_Flat");
					this.OnFee_CC_Visa_FlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_CC_MC_PCT", DbType="Real")]
		public System.Nullable<float> Fee_CC_MC_PCT
		{
			get
			{
				return this._Fee_CC_MC_PCT;
			}
			set
			{
				if ((this._Fee_CC_MC_PCT != value))
				{
					this.OnFee_CC_MC_PCTChanging(value);
					this.SendPropertyChanging();
					this._Fee_CC_MC_PCT = value;
					this.SendPropertyChanged("Fee_CC_MC_PCT");
					this.OnFee_CC_MC_PCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_CC_MC_Flat", DbType="Money")]
		public System.Nullable<decimal> Fee_CC_MC_Flat
		{
			get
			{
				return this._Fee_CC_MC_Flat;
			}
			set
			{
				if ((this._Fee_CC_MC_Flat != value))
				{
					this.OnFee_CC_MC_FlatChanging(value);
					this.SendPropertyChanging();
					this._Fee_CC_MC_Flat = value;
					this.SendPropertyChanged("Fee_CC_MC_Flat");
					this.OnFee_CC_MC_FlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_CC_Amex_Pct", DbType="Real")]
		public System.Nullable<float> Fee_CC_Amex_Pct
		{
			get
			{
				return this._Fee_CC_Amex_Pct;
			}
			set
			{
				if ((this._Fee_CC_Amex_Pct != value))
				{
					this.OnFee_CC_Amex_PctChanging(value);
					this.SendPropertyChanging();
					this._Fee_CC_Amex_Pct = value;
					this.SendPropertyChanged("Fee_CC_Amex_Pct");
					this.OnFee_CC_Amex_PctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_CC_Amex_Flat", DbType="Money")]
		public System.Nullable<decimal> Fee_CC_Amex_Flat
		{
			get
			{
				return this._Fee_CC_Amex_Flat;
			}
			set
			{
				if ((this._Fee_CC_Amex_Flat != value))
				{
					this.OnFee_CC_Amex_FlatChanging(value);
					this.SendPropertyChanging();
					this._Fee_CC_Amex_Flat = value;
					this.SendPropertyChanged("Fee_CC_Amex_Flat");
					this.OnFee_CC_Amex_FlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_CC_Discover_Pct", DbType="Real")]
		public System.Nullable<float> Fee_CC_Discover_Pct
		{
			get
			{
				return this._Fee_CC_Discover_Pct;
			}
			set
			{
				if ((this._Fee_CC_Discover_Pct != value))
				{
					this.OnFee_CC_Discover_PctChanging(value);
					this.SendPropertyChanging();
					this._Fee_CC_Discover_Pct = value;
					this.SendPropertyChanged("Fee_CC_Discover_Pct");
					this.OnFee_CC_Discover_PctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_CC_Discover_Flat", DbType="Money")]
		public System.Nullable<decimal> Fee_CC_Discover_Flat
		{
			get
			{
				return this._Fee_CC_Discover_Flat;
			}
			set
			{
				if ((this._Fee_CC_Discover_Flat != value))
				{
					this.OnFee_CC_Discover_FlatChanging(value);
					this.SendPropertyChanging();
					this._Fee_CC_Discover_Flat = value;
					this.SendPropertyChanged("Fee_CC_Discover_Flat");
					this.OnFee_CC_Discover_FlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_CC_Diners_Pct", DbType="Real")]
		public System.Nullable<float> Fee_CC_Diners_Pct
		{
			get
			{
				return this._Fee_CC_Diners_Pct;
			}
			set
			{
				if ((this._Fee_CC_Diners_Pct != value))
				{
					this.OnFee_CC_Diners_PctChanging(value);
					this.SendPropertyChanging();
					this._Fee_CC_Diners_Pct = value;
					this.SendPropertyChanged("Fee_CC_Diners_Pct");
					this.OnFee_CC_Diners_PctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_CC_Diners_Flat", DbType="Money")]
		public System.Nullable<decimal> Fee_CC_Diners_Flat
		{
			get
			{
				return this._Fee_CC_Diners_Flat;
			}
			set
			{
				if ((this._Fee_CC_Diners_Flat != value))
				{
					this.OnFee_CC_Diners_FlatChanging(value);
					this.SendPropertyChanging();
					this._Fee_CC_Diners_Flat = value;
					this.SendPropertyChanged("Fee_CC_Diners_Flat");
					this.OnFee_CC_Diners_FlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_CC_Minimum", DbType="Money")]
		public System.Nullable<decimal> Fee_CC_Minimum
		{
			get
			{
				return this._Fee_CC_Minimum;
			}
			set
			{
				if ((this._Fee_CC_Minimum != value))
				{
					this.OnFee_CC_MinimumChanging(value);
					this.SendPropertyChanging();
					this._Fee_CC_Minimum = value;
					this.SendPropertyChanged("Fee_CC_Minimum");
					this.OnFee_CC_MinimumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_Event_Setup", DbType="Money")]
		public System.Nullable<decimal> Fee_Event_Setup
		{
			get
			{
				return this._Fee_Event_Setup;
			}
			set
			{
				if ((this._Fee_Event_Setup != value))
				{
					this.OnFee_Event_SetupChanging(value);
					this.SendPropertyChanging();
					this._Fee_Event_Setup = value;
					this.SendPropertyChanged("Fee_Event_Setup");
					this.OnFee_Event_SetupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_Waitlist_Setup", DbType="Money")]
		public System.Nullable<decimal> Fee_Waitlist_Setup
		{
			get
			{
				return this._Fee_Waitlist_Setup;
			}
			set
			{
				if ((this._Fee_Waitlist_Setup != value))
				{
					this.OnFee_Waitlist_SetupChanging(value);
					this.SendPropertyChanging();
					this._Fee_Waitlist_Setup = value;
					this.SendPropertyChanged("Fee_Waitlist_Setup");
					this.OnFee_Waitlist_SetupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_1", DbType="Money")]
		public System.Nullable<decimal> Fee_1
		{
			get
			{
				return this._Fee_1;
			}
			set
			{
				if ((this._Fee_1 != value))
				{
					this.OnFee_1Changing(value);
					this.SendPropertyChanging();
					this._Fee_1 = value;
					this.SendPropertyChanged("Fee_1");
					this.OnFee_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_2", DbType="Money")]
		public System.Nullable<decimal> Fee_2
		{
			get
			{
				return this._Fee_2;
			}
			set
			{
				if ((this._Fee_2 != value))
				{
					this.OnFee_2Changing(value);
					this.SendPropertyChanging();
					this._Fee_2 = value;
					this.SendPropertyChanged("Fee_2");
					this.OnFee_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_Survey", DbType="Money")]
		public System.Nullable<decimal> Fee_Survey
		{
			get
			{
				return this._Fee_Survey;
			}
			set
			{
				if ((this._Fee_Survey != value))
				{
					this.OnFee_SurveyChanging(value);
					this.SendPropertyChanging();
					this._Fee_Survey = value;
					this.SendPropertyChanged("Fee_Survey");
					this.OnFee_SurveyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_One_Time", DbType="Money")]
		public System.Nullable<decimal> Fee_One_Time
		{
			get
			{
				return this._Fee_One_Time;
			}
			set
			{
				if ((this._Fee_One_Time != value))
				{
					this.OnFee_One_TimeChanging(value);
					this.SendPropertyChanging();
					this._Fee_One_Time = value;
					this.SendPropertyChanged("Fee_One_Time");
					this.OnFee_One_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_Apply_Flat", DbType="Bit")]
		public System.Nullable<bool> Fee_Apply_Flat
		{
			get
			{
				return this._Fee_Apply_Flat;
			}
			set
			{
				if ((this._Fee_Apply_Flat != value))
				{
					this.OnFee_Apply_FlatChanging(value);
					this.SendPropertyChanging();
					this._Fee_Apply_Flat = value;
					this.SendPropertyChanged("Fee_Apply_Flat");
					this.OnFee_Apply_FlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_Reminder", DbType="Money")]
		public System.Nullable<decimal> Fee_Reminder
		{
			get
			{
				return this._Fee_Reminder;
			}
			set
			{
				if ((this._Fee_Reminder != value))
				{
					this.OnFee_ReminderChanging(value);
					this.SendPropertyChanging();
					this._Fee_Reminder = value;
					this.SendPropertyChanged("Fee_Reminder");
					this.OnFee_ReminderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_Email", DbType="SmallMoney")]
		public System.Nullable<decimal> Fee_Email
		{
			get
			{
				return this._Fee_Email;
			}
			set
			{
				if ((this._Fee_Email != value))
				{
					this.OnFee_EmailChanging(value);
					this.SendPropertyChanging();
					this._Fee_Email = value;
					this.SendPropertyChanged("Fee_Email");
					this.OnFee_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_Email_Flat", DbType="Bit")]
		public System.Nullable<bool> Fee_Email_Flat
		{
			get
			{
				return this._Fee_Email_Flat;
			}
			set
			{
				if ((this._Fee_Email_Flat != value))
				{
					this.OnFee_Email_FlatChanging(value);
					this.SendPropertyChanging();
					this._Fee_Email_Flat = value;
					this.SendPropertyChanged("Fee_Email_Flat");
					this.OnFee_Email_FlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_Charge_For_Parent", DbType="Bit")]
		public System.Nullable<bool> Fee_Charge_For_Parent
		{
			get
			{
				return this._Fee_Charge_For_Parent;
			}
			set
			{
				if ((this._Fee_Charge_For_Parent != value))
				{
					this.OnFee_Charge_For_ParentChanging(value);
					this.SendPropertyChanging();
					this._Fee_Charge_For_Parent = value;
					this.SendPropertyChanged("Fee_Charge_For_Parent");
					this.OnFee_Charge_For_ParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_Chargeback_Fee", DbType="Money")]
		public System.Nullable<decimal> Fee_Chargeback_Fee
		{
			get
			{
				return this._Fee_Chargeback_Fee;
			}
			set
			{
				if ((this._Fee_Chargeback_Fee != value))
				{
					this.OnFee_Chargeback_FeeChanging(value);
					this.SendPropertyChanging();
					this._Fee_Chargeback_Fee = value;
					this.SendPropertyChanged("Fee_Chargeback_Fee");
					this.OnFee_Chargeback_FeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseCurrencyCode", DbType="VarChar(3)")]
		public string BaseCurrencyCode
		{
			get
			{
				return this._BaseCurrencyCode;
			}
			set
			{
				if ((this._BaseCurrencyCode != value))
				{
					this.OnBaseCurrencyCodeChanging(value);
					this.SendPropertyChanging();
					this._BaseCurrencyCode = value;
					this.SendPropertyChanged("BaseCurrencyCode");
					this.OnBaseCurrencyCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_PayWithCreditCard", DbType="Bit")]
		public System.Nullable<bool> Fee_PayWithCreditCard
		{
			get
			{
				return this._Fee_PayWithCreditCard;
			}
			set
			{
				if ((this._Fee_PayWithCreditCard != value))
				{
					this.OnFee_PayWithCreditCardChanging(value);
					this.SendPropertyChanging();
					this._Fee_PayWithCreditCard = value;
					this.SendPropertyChanged("Fee_PayWithCreditCard");
					this.OnFee_PayWithCreditCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Add_Date
		{
			get
			{
				return this._Add_Date;
			}
			set
			{
				if ((this._Add_Date != value))
				{
					this.OnAdd_DateChanging(value);
					this.SendPropertyChanging();
					this._Add_Date = value;
					this.SendPropertyChanged("Add_Date");
					this.OnAdd_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add_By", DbType="NVarChar(50)")]
		public string Add_By
		{
			get
			{
				return this._Add_By;
			}
			set
			{
				if ((this._Add_By != value))
				{
					this.OnAdd_ByChanging(value);
					this.SendPropertyChanging();
					this._Add_By = value;
					this.SendPropertyChanged("Add_By");
					this.OnAdd_ByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mod_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Mod_Date
		{
			get
			{
				return this._Mod_Date;
			}
			set
			{
				if ((this._Mod_Date != value))
				{
					this.OnMod_DateChanging(value);
					this.SendPropertyChanging();
					this._Mod_Date = value;
					this.SendPropertyChanged("Mod_Date");
					this.OnMod_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mod_By", DbType="NVarChar(50)")]
		public string Mod_By
		{
			get
			{
				return this._Mod_By;
			}
			set
			{
				if ((this._Mod_By != value))
				{
					this.OnMod_ByChanging(value);
					this.SendPropertyChanging();
					this._Mod_By = value;
					this.SendPropertyChanged("Mod_By");
					this.OnMod_ByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventBillingId", DbType="Int")]
		public System.Nullable<int> EventBillingId
		{
			get
			{
				return this._EventBillingId;
			}
			set
			{
				if ((this._EventBillingId != value))
				{
					this.OnEventBillingIdChanging(value);
					this.SendPropertyChanging();
					this._EventBillingId = value;
					this.SendPropertyChanged("EventBillingId");
					this.OnEventBillingIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ukAccount", DbType="Bit")]
		public System.Nullable<bool> ukAccount
		{
			get
			{
				return this._ukAccount;
			}
			set
			{
				if ((this._ukAccount != value))
				{
					this.OnukAccountChanging(value);
					this.SendPropertyChanging();
					this._ukAccount = value;
					this.SendPropertyChanged("ukAccount");
					this.OnukAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_collectVatTax", DbType="Bit")]
		public System.Nullable<bool> collectVatTax
		{
			get
			{
				return this._collectVatTax;
			}
			set
			{
				if ((this._collectVatTax != value))
				{
					this.OncollectVatTaxChanging(value);
					this.SendPropertyChanging();
					this._collectVatTax = value;
					this.SendPropertyChanged("collectVatTax");
					this.OncollectVatTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VatTaxId", DbType="NVarChar(50)")]
		public string VatTaxId
		{
			get
			{
				return this._VatTaxId;
			}
			set
			{
				if ((this._VatTaxId != value))
				{
					this.OnVatTaxIdChanging(value);
					this.SendPropertyChanging();
					this._VatTaxId = value;
					this.SendPropertyChanged("VatTaxId");
					this.OnVatTaxIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceEmailDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> InvoiceEmailDate
		{
			get
			{
				return this._InvoiceEmailDate;
			}
			set
			{
				if ((this._InvoiceEmailDate != value))
				{
					this.OnInvoiceEmailDateChanging(value);
					this.SendPropertyChanging();
					this._InvoiceEmailDate = value;
					this.SendPropertyChanged("InvoiceEmailDate");
					this.OnInvoiceEmailDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CustomerInvoice_CustomerInvoiceItem", Storage="_CustomerInvoiceItems", ThisKey="Id", OtherKey="InvoiceId")]
		public EntitySet<CustomerInvoiceItem> CustomerInvoiceItems
		{
			get
			{
				return this._CustomerInvoiceItems;
			}
			set
			{
				this._CustomerInvoiceItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CustomerInvoiceItems(CustomerInvoiceItem entity)
		{
			this.SendPropertyChanging();
			entity.CustomerInvoice = this;
		}
		
		private void detach_CustomerInvoiceItems(CustomerInvoiceItem entity)
		{
			this.SendPropertyChanging();
			entity.CustomerInvoice = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerTransactions")]
	public partial class CustomerTransaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _CustomerId;
		
		private System.Nullable<int> _TypeId;
		
		private string _InvoiceNumbers;
		
		private System.Nullable<decimal> _TransAmount;
		
		private System.Nullable<System.DateTime> _TransDate;
		
		private string _ccNumber;
		
		private System.Nullable<System.DateTime> _ccExpDate;
		
		private string _ccName;
		
		private string _ccRefNumber;
		
		private string _Notes;
		
		private System.Nullable<bool> _Voided;
		
		private System.Nullable<decimal> _VoidedAmount;
		
		private System.DateTime _Add_Date;
		
		private string _Add_By;
		
		private System.DateTime _Mod_Date;
		
		private string _Mod_By;
		
		private System.Nullable<bool> _LoggedInQB;
		
		private string _OrderId;
		
		private System.Nullable<System.DateTime> _Oracle_sentto;
		
		private System.Nullable<int> _Oracle_CashReceiptID;
		
		private System.Nullable<long> _Oracle_ReceiptNum;
		
		private string _Oracle_InvoiceNum;
		
		private System.Nullable<int> _Oracle_CheckNum;
		
		private System.Nullable<int> _amsMerchantAccountID;
		
		private string _processor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCustomerIdChanging(int value);
    partial void OnCustomerIdChanged();
    partial void OnTypeIdChanging(System.Nullable<int> value);
    partial void OnTypeIdChanged();
    partial void OnInvoiceNumbersChanging(string value);
    partial void OnInvoiceNumbersChanged();
    partial void OnTransAmountChanging(System.Nullable<decimal> value);
    partial void OnTransAmountChanged();
    partial void OnTransDateChanging(System.Nullable<System.DateTime> value);
    partial void OnTransDateChanged();
    partial void OnccNumberChanging(string value);
    partial void OnccNumberChanged();
    partial void OnccExpDateChanging(System.Nullable<System.DateTime> value);
    partial void OnccExpDateChanged();
    partial void OnccNameChanging(string value);
    partial void OnccNameChanged();
    partial void OnccRefNumberChanging(string value);
    partial void OnccRefNumberChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnVoidedChanging(System.Nullable<bool> value);
    partial void OnVoidedChanged();
    partial void OnVoidedAmountChanging(System.Nullable<decimal> value);
    partial void OnVoidedAmountChanged();
    partial void OnAdd_DateChanging(System.DateTime value);
    partial void OnAdd_DateChanged();
    partial void OnAdd_ByChanging(string value);
    partial void OnAdd_ByChanged();
    partial void OnMod_DateChanging(System.DateTime value);
    partial void OnMod_DateChanged();
    partial void OnMod_ByChanging(string value);
    partial void OnMod_ByChanged();
    partial void OnLoggedInQBChanging(System.Nullable<bool> value);
    partial void OnLoggedInQBChanged();
    partial void OnOrderIdChanging(string value);
    partial void OnOrderIdChanged();
    partial void OnOracle_senttoChanging(System.Nullable<System.DateTime> value);
    partial void OnOracle_senttoChanged();
    partial void OnOracle_CashReceiptIDChanging(System.Nullable<int> value);
    partial void OnOracle_CashReceiptIDChanged();
    partial void OnOracle_ReceiptNumChanging(System.Nullable<long> value);
    partial void OnOracle_ReceiptNumChanged();
    partial void OnOracle_InvoiceNumChanging(string value);
    partial void OnOracle_InvoiceNumChanged();
    partial void OnOracle_CheckNumChanging(System.Nullable<int> value);
    partial void OnOracle_CheckNumChanged();
    partial void OnamsMerchantAccountIDChanging(System.Nullable<int> value);
    partial void OnamsMerchantAccountIDChanged();
    partial void OnprocessorChanging(string value);
    partial void OnprocessorChanged();
    #endregion
		
		public CustomerTransaction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", DbType="Int NOT NULL")]
		public int CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeId", DbType="Int")]
		public System.Nullable<int> TypeId
		{
			get
			{
				return this._TypeId;
			}
			set
			{
				if ((this._TypeId != value))
				{
					this.OnTypeIdChanging(value);
					this.SendPropertyChanging();
					this._TypeId = value;
					this.SendPropertyChanged("TypeId");
					this.OnTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumbers", DbType="VarChar(255)")]
		public string InvoiceNumbers
		{
			get
			{
				return this._InvoiceNumbers;
			}
			set
			{
				if ((this._InvoiceNumbers != value))
				{
					this.OnInvoiceNumbersChanging(value);
					this.SendPropertyChanging();
					this._InvoiceNumbers = value;
					this.SendPropertyChanged("InvoiceNumbers");
					this.OnInvoiceNumbersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransAmount", DbType="Money")]
		public System.Nullable<decimal> TransAmount
		{
			get
			{
				return this._TransAmount;
			}
			set
			{
				if ((this._TransAmount != value))
				{
					this.OnTransAmountChanging(value);
					this.SendPropertyChanging();
					this._TransAmount = value;
					this.SendPropertyChanged("TransAmount");
					this.OnTransAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TransDate
		{
			get
			{
				return this._TransDate;
			}
			set
			{
				if ((this._TransDate != value))
				{
					this.OnTransDateChanging(value);
					this.SendPropertyChanging();
					this._TransDate = value;
					this.SendPropertyChanged("TransDate");
					this.OnTransDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccNumber", DbType="VarChar(100)")]
		public string ccNumber
		{
			get
			{
				return this._ccNumber;
			}
			set
			{
				if ((this._ccNumber != value))
				{
					this.OnccNumberChanging(value);
					this.SendPropertyChanging();
					this._ccNumber = value;
					this.SendPropertyChanged("ccNumber");
					this.OnccNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccExpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ccExpDate
		{
			get
			{
				return this._ccExpDate;
			}
			set
			{
				if ((this._ccExpDate != value))
				{
					this.OnccExpDateChanging(value);
					this.SendPropertyChanging();
					this._ccExpDate = value;
					this.SendPropertyChanged("ccExpDate");
					this.OnccExpDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccName", DbType="VarChar(50)")]
		public string ccName
		{
			get
			{
				return this._ccName;
			}
			set
			{
				if ((this._ccName != value))
				{
					this.OnccNameChanging(value);
					this.SendPropertyChanging();
					this._ccName = value;
					this.SendPropertyChanged("ccName");
					this.OnccNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccRefNumber", DbType="VarChar(50)")]
		public string ccRefNumber
		{
			get
			{
				return this._ccRefNumber;
			}
			set
			{
				if ((this._ccRefNumber != value))
				{
					this.OnccRefNumberChanging(value);
					this.SendPropertyChanging();
					this._ccRefNumber = value;
					this.SendPropertyChanged("ccRefNumber");
					this.OnccRefNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(MAX)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voided", DbType="Bit")]
		public System.Nullable<bool> Voided
		{
			get
			{
				return this._Voided;
			}
			set
			{
				if ((this._Voided != value))
				{
					this.OnVoidedChanging(value);
					this.SendPropertyChanging();
					this._Voided = value;
					this.SendPropertyChanged("Voided");
					this.OnVoidedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VoidedAmount", DbType="Money")]
		public System.Nullable<decimal> VoidedAmount
		{
			get
			{
				return this._VoidedAmount;
			}
			set
			{
				if ((this._VoidedAmount != value))
				{
					this.OnVoidedAmountChanging(value);
					this.SendPropertyChanging();
					this._VoidedAmount = value;
					this.SendPropertyChanged("VoidedAmount");
					this.OnVoidedAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Add_Date
		{
			get
			{
				return this._Add_Date;
			}
			set
			{
				if ((this._Add_Date != value))
				{
					this.OnAdd_DateChanging(value);
					this.SendPropertyChanging();
					this._Add_Date = value;
					this.SendPropertyChanged("Add_Date");
					this.OnAdd_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add_By", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Add_By
		{
			get
			{
				return this._Add_By;
			}
			set
			{
				if ((this._Add_By != value))
				{
					this.OnAdd_ByChanging(value);
					this.SendPropertyChanging();
					this._Add_By = value;
					this.SendPropertyChanged("Add_By");
					this.OnAdd_ByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mod_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Mod_Date
		{
			get
			{
				return this._Mod_Date;
			}
			set
			{
				if ((this._Mod_Date != value))
				{
					this.OnMod_DateChanging(value);
					this.SendPropertyChanging();
					this._Mod_Date = value;
					this.SendPropertyChanged("Mod_Date");
					this.OnMod_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mod_By", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Mod_By
		{
			get
			{
				return this._Mod_By;
			}
			set
			{
				if ((this._Mod_By != value))
				{
					this.OnMod_ByChanging(value);
					this.SendPropertyChanging();
					this._Mod_By = value;
					this.SendPropertyChanged("Mod_By");
					this.OnMod_ByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoggedInQB", DbType="Bit")]
		public System.Nullable<bool> LoggedInQB
		{
			get
			{
				return this._LoggedInQB;
			}
			set
			{
				if ((this._LoggedInQB != value))
				{
					this.OnLoggedInQBChanging(value);
					this.SendPropertyChanging();
					this._LoggedInQB = value;
					this.SendPropertyChanged("LoggedInQB");
					this.OnLoggedInQBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderId", DbType="VarChar(50)")]
		public string OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				if ((this._OrderId != value))
				{
					this.OnOrderIdChanging(value);
					this.SendPropertyChanging();
					this._OrderId = value;
					this.SendPropertyChanged("OrderId");
					this.OnOrderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oracle_sentto", DbType="DateTime")]
		public System.Nullable<System.DateTime> Oracle_sentto
		{
			get
			{
				return this._Oracle_sentto;
			}
			set
			{
				if ((this._Oracle_sentto != value))
				{
					this.OnOracle_senttoChanging(value);
					this.SendPropertyChanging();
					this._Oracle_sentto = value;
					this.SendPropertyChanged("Oracle_sentto");
					this.OnOracle_senttoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oracle_CashReceiptID", DbType="Int")]
		public System.Nullable<int> Oracle_CashReceiptID
		{
			get
			{
				return this._Oracle_CashReceiptID;
			}
			set
			{
				if ((this._Oracle_CashReceiptID != value))
				{
					this.OnOracle_CashReceiptIDChanging(value);
					this.SendPropertyChanging();
					this._Oracle_CashReceiptID = value;
					this.SendPropertyChanged("Oracle_CashReceiptID");
					this.OnOracle_CashReceiptIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oracle_ReceiptNum", DbType="BigInt")]
		public System.Nullable<long> Oracle_ReceiptNum
		{
			get
			{
				return this._Oracle_ReceiptNum;
			}
			set
			{
				if ((this._Oracle_ReceiptNum != value))
				{
					this.OnOracle_ReceiptNumChanging(value);
					this.SendPropertyChanging();
					this._Oracle_ReceiptNum = value;
					this.SendPropertyChanged("Oracle_ReceiptNum");
					this.OnOracle_ReceiptNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oracle_InvoiceNum", DbType="NVarChar(30)")]
		public string Oracle_InvoiceNum
		{
			get
			{
				return this._Oracle_InvoiceNum;
			}
			set
			{
				if ((this._Oracle_InvoiceNum != value))
				{
					this.OnOracle_InvoiceNumChanging(value);
					this.SendPropertyChanging();
					this._Oracle_InvoiceNum = value;
					this.SendPropertyChanged("Oracle_InvoiceNum");
					this.OnOracle_InvoiceNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oracle_CheckNum", DbType="Int")]
		public System.Nullable<int> Oracle_CheckNum
		{
			get
			{
				return this._Oracle_CheckNum;
			}
			set
			{
				if ((this._Oracle_CheckNum != value))
				{
					this.OnOracle_CheckNumChanging(value);
					this.SendPropertyChanging();
					this._Oracle_CheckNum = value;
					this.SendPropertyChanged("Oracle_CheckNum");
					this.OnOracle_CheckNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amsMerchantAccountID", DbType="Int")]
		public System.Nullable<int> amsMerchantAccountID
		{
			get
			{
				return this._amsMerchantAccountID;
			}
			set
			{
				if ((this._amsMerchantAccountID != value))
				{
					this.OnamsMerchantAccountIDChanging(value);
					this.SendPropertyChanging();
					this._amsMerchantAccountID = value;
					this.SendPropertyChanged("amsMerchantAccountID");
					this.OnamsMerchantAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_processor", DbType="Char(2)")]
		public string processor
		{
			get
			{
				return this._processor;
			}
			set
			{
				if ((this._processor != value))
				{
					this.OnprocessorChanging(value);
					this.SendPropertyChanging();
					this._processor = value;
					this.SendPropertyChanged("processor");
					this.OnprocessorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sessions")]
	public partial class Session : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private System.Nullable<bool> _IsUpdate;
		
		private int _regTypePassed;
		
		private System.Nullable<byte> _MethodId;
		
		private bool _InternalReg;
		
		private System.Nullable<bool> _AdminReg;
		
		private System.Nullable<int> _UserId;
		
		private string _UserName;
		
		private System.Nullable<int> _CustomerId;
		
		private int _EventId;
		
		private System.Nullable<int> _AttendeeId;
		
		private System.Nullable<int> _RegisterId;
		
		private System.Nullable<int> _OldRegisterId;
		
		private System.Nullable<int> _GroupId;
		
		private System.Nullable<int> _RegTypeId;
		
		private System.Nullable<bool> _IsGroup;
		
		private bool _IsMember;
		
		private bool _IsCart;
		
		private bool _isDuplicateLogin;
		
		private bool _useNewSecurity;
		
		private System.Nullable<decimal> _AmountDue;
		
		private System.Nullable<decimal> _PaymentAmount;
		
		private System.Nullable<byte> _PasswordCount;
		
		private System.Nullable<bool> _SendConfirm;
		
		private System.Nullable<int> _DBReadId;
		
		private System.Nullable<int> _DBWriteId;
		
		private System.DateTime _Add_Date;
		
		private System.Nullable<bool> _RegonlineSuperAdmin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnIsUpdateChanging(System.Nullable<bool> value);
    partial void OnIsUpdateChanged();
    partial void OnregTypePassedChanging(int value);
    partial void OnregTypePassedChanged();
    partial void OnMethodIdChanging(System.Nullable<byte> value);
    partial void OnMethodIdChanged();
    partial void OnInternalRegChanging(bool value);
    partial void OnInternalRegChanged();
    partial void OnAdminRegChanging(System.Nullable<bool> value);
    partial void OnAdminRegChanged();
    partial void OnUserIdChanging(System.Nullable<int> value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnCustomerIdChanging(System.Nullable<int> value);
    partial void OnCustomerIdChanged();
    partial void OnEventIdChanging(int value);
    partial void OnEventIdChanged();
    partial void OnAttendeeIdChanging(System.Nullable<int> value);
    partial void OnAttendeeIdChanged();
    partial void OnRegisterIdChanging(System.Nullable<int> value);
    partial void OnRegisterIdChanged();
    partial void OnOldRegisterIdChanging(System.Nullable<int> value);
    partial void OnOldRegisterIdChanged();
    partial void OnGroupIdChanging(System.Nullable<int> value);
    partial void OnGroupIdChanged();
    partial void OnRegTypeIdChanging(System.Nullable<int> value);
    partial void OnRegTypeIdChanged();
    partial void OnIsGroupChanging(System.Nullable<bool> value);
    partial void OnIsGroupChanged();
    partial void OnIsMemberChanging(bool value);
    partial void OnIsMemberChanged();
    partial void OnIsCartChanging(bool value);
    partial void OnIsCartChanged();
    partial void OnisDuplicateLoginChanging(bool value);
    partial void OnisDuplicateLoginChanged();
    partial void OnuseNewSecurityChanging(bool value);
    partial void OnuseNewSecurityChanged();
    partial void OnAmountDueChanging(System.Nullable<decimal> value);
    partial void OnAmountDueChanged();
    partial void OnPaymentAmountChanging(System.Nullable<decimal> value);
    partial void OnPaymentAmountChanged();
    partial void OnPasswordCountChanging(System.Nullable<byte> value);
    partial void OnPasswordCountChanged();
    partial void OnSendConfirmChanging(System.Nullable<bool> value);
    partial void OnSendConfirmChanged();
    partial void OnDBReadIdChanging(System.Nullable<int> value);
    partial void OnDBReadIdChanged();
    partial void OnDBWriteIdChanging(System.Nullable<int> value);
    partial void OnDBWriteIdChanged();
    partial void OnAdd_DateChanging(System.DateTime value);
    partial void OnAdd_DateChanged();
    partial void OnRegonlineSuperAdminChanging(System.Nullable<bool> value);
    partial void OnRegonlineSuperAdminChanged();
    #endregion
		
		public Session()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsUpdate", DbType="Bit")]
		public System.Nullable<bool> IsUpdate
		{
			get
			{
				return this._IsUpdate;
			}
			set
			{
				if ((this._IsUpdate != value))
				{
					this.OnIsUpdateChanging(value);
					this.SendPropertyChanging();
					this._IsUpdate = value;
					this.SendPropertyChanged("IsUpdate");
					this.OnIsUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regTypePassed", DbType="Int NOT NULL")]
		public int regTypePassed
		{
			get
			{
				return this._regTypePassed;
			}
			set
			{
				if ((this._regTypePassed != value))
				{
					this.OnregTypePassedChanging(value);
					this.SendPropertyChanging();
					this._regTypePassed = value;
					this.SendPropertyChanged("regTypePassed");
					this.OnregTypePassedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MethodId", DbType="TinyInt")]
		public System.Nullable<byte> MethodId
		{
			get
			{
				return this._MethodId;
			}
			set
			{
				if ((this._MethodId != value))
				{
					this.OnMethodIdChanging(value);
					this.SendPropertyChanging();
					this._MethodId = value;
					this.SendPropertyChanged("MethodId");
					this.OnMethodIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalReg", DbType="Bit NOT NULL")]
		public bool InternalReg
		{
			get
			{
				return this._InternalReg;
			}
			set
			{
				if ((this._InternalReg != value))
				{
					this.OnInternalRegChanging(value);
					this.SendPropertyChanging();
					this._InternalReg = value;
					this.SendPropertyChanged("InternalReg");
					this.OnInternalRegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminReg", DbType="Bit")]
		public System.Nullable<bool> AdminReg
		{
			get
			{
				return this._AdminReg;
			}
			set
			{
				if ((this._AdminReg != value))
				{
					this.OnAdminRegChanging(value);
					this.SendPropertyChanging();
					this._AdminReg = value;
					this.SendPropertyChanged("AdminReg");
					this.OnAdminRegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", DbType="Int")]
		public System.Nullable<int> CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventId", DbType="Int NOT NULL")]
		public int EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				if ((this._EventId != value))
				{
					this.OnEventIdChanging(value);
					this.SendPropertyChanging();
					this._EventId = value;
					this.SendPropertyChanged("EventId");
					this.OnEventIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendeeId", DbType="Int")]
		public System.Nullable<int> AttendeeId
		{
			get
			{
				return this._AttendeeId;
			}
			set
			{
				if ((this._AttendeeId != value))
				{
					this.OnAttendeeIdChanging(value);
					this.SendPropertyChanging();
					this._AttendeeId = value;
					this.SendPropertyChanged("AttendeeId");
					this.OnAttendeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisterId", DbType="Int")]
		public System.Nullable<int> RegisterId
		{
			get
			{
				return this._RegisterId;
			}
			set
			{
				if ((this._RegisterId != value))
				{
					this.OnRegisterIdChanging(value);
					this.SendPropertyChanging();
					this._RegisterId = value;
					this.SendPropertyChanged("RegisterId");
					this.OnRegisterIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldRegisterId", DbType="Int")]
		public System.Nullable<int> OldRegisterId
		{
			get
			{
				return this._OldRegisterId;
			}
			set
			{
				if ((this._OldRegisterId != value))
				{
					this.OnOldRegisterIdChanging(value);
					this.SendPropertyChanging();
					this._OldRegisterId = value;
					this.SendPropertyChanged("OldRegisterId");
					this.OnOldRegisterIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="Int")]
		public System.Nullable<int> GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					this.OnGroupIdChanging(value);
					this.SendPropertyChanging();
					this._GroupId = value;
					this.SendPropertyChanged("GroupId");
					this.OnGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegTypeId", DbType="Int")]
		public System.Nullable<int> RegTypeId
		{
			get
			{
				return this._RegTypeId;
			}
			set
			{
				if ((this._RegTypeId != value))
				{
					this.OnRegTypeIdChanging(value);
					this.SendPropertyChanging();
					this._RegTypeId = value;
					this.SendPropertyChanged("RegTypeId");
					this.OnRegTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsGroup", DbType="Bit")]
		public System.Nullable<bool> IsGroup
		{
			get
			{
				return this._IsGroup;
			}
			set
			{
				if ((this._IsGroup != value))
				{
					this.OnIsGroupChanging(value);
					this.SendPropertyChanging();
					this._IsGroup = value;
					this.SendPropertyChanged("IsGroup");
					this.OnIsGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMember", DbType="Bit NOT NULL")]
		public bool IsMember
		{
			get
			{
				return this._IsMember;
			}
			set
			{
				if ((this._IsMember != value))
				{
					this.OnIsMemberChanging(value);
					this.SendPropertyChanging();
					this._IsMember = value;
					this.SendPropertyChanged("IsMember");
					this.OnIsMemberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCart", DbType="Bit NOT NULL")]
		public bool IsCart
		{
			get
			{
				return this._IsCart;
			}
			set
			{
				if ((this._IsCart != value))
				{
					this.OnIsCartChanging(value);
					this.SendPropertyChanging();
					this._IsCart = value;
					this.SendPropertyChanged("IsCart");
					this.OnIsCartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDuplicateLogin", DbType="Bit NOT NULL")]
		public bool isDuplicateLogin
		{
			get
			{
				return this._isDuplicateLogin;
			}
			set
			{
				if ((this._isDuplicateLogin != value))
				{
					this.OnisDuplicateLoginChanging(value);
					this.SendPropertyChanging();
					this._isDuplicateLogin = value;
					this.SendPropertyChanged("isDuplicateLogin");
					this.OnisDuplicateLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_useNewSecurity", DbType="Bit NOT NULL")]
		public bool useNewSecurity
		{
			get
			{
				return this._useNewSecurity;
			}
			set
			{
				if ((this._useNewSecurity != value))
				{
					this.OnuseNewSecurityChanging(value);
					this.SendPropertyChanging();
					this._useNewSecurity = value;
					this.SendPropertyChanged("useNewSecurity");
					this.OnuseNewSecurityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmountDue", DbType="Money")]
		public System.Nullable<decimal> AmountDue
		{
			get
			{
				return this._AmountDue;
			}
			set
			{
				if ((this._AmountDue != value))
				{
					this.OnAmountDueChanging(value);
					this.SendPropertyChanging();
					this._AmountDue = value;
					this.SendPropertyChanged("AmountDue");
					this.OnAmountDueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentAmount", DbType="Money")]
		public System.Nullable<decimal> PaymentAmount
		{
			get
			{
				return this._PaymentAmount;
			}
			set
			{
				if ((this._PaymentAmount != value))
				{
					this.OnPaymentAmountChanging(value);
					this.SendPropertyChanging();
					this._PaymentAmount = value;
					this.SendPropertyChanged("PaymentAmount");
					this.OnPaymentAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordCount", DbType="TinyInt")]
		public System.Nullable<byte> PasswordCount
		{
			get
			{
				return this._PasswordCount;
			}
			set
			{
				if ((this._PasswordCount != value))
				{
					this.OnPasswordCountChanging(value);
					this.SendPropertyChanging();
					this._PasswordCount = value;
					this.SendPropertyChanged("PasswordCount");
					this.OnPasswordCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendConfirm", DbType="Bit")]
		public System.Nullable<bool> SendConfirm
		{
			get
			{
				return this._SendConfirm;
			}
			set
			{
				if ((this._SendConfirm != value))
				{
					this.OnSendConfirmChanging(value);
					this.SendPropertyChanging();
					this._SendConfirm = value;
					this.SendPropertyChanged("SendConfirm");
					this.OnSendConfirmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBReadId", DbType="Int")]
		public System.Nullable<int> DBReadId
		{
			get
			{
				return this._DBReadId;
			}
			set
			{
				if ((this._DBReadId != value))
				{
					this.OnDBReadIdChanging(value);
					this.SendPropertyChanging();
					this._DBReadId = value;
					this.SendPropertyChanged("DBReadId");
					this.OnDBReadIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBWriteId", DbType="Int")]
		public System.Nullable<int> DBWriteId
		{
			get
			{
				return this._DBWriteId;
			}
			set
			{
				if ((this._DBWriteId != value))
				{
					this.OnDBWriteIdChanging(value);
					this.SendPropertyChanging();
					this._DBWriteId = value;
					this.SendPropertyChanged("DBWriteId");
					this.OnDBWriteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Add_Date
		{
			get
			{
				return this._Add_Date;
			}
			set
			{
				if ((this._Add_Date != value))
				{
					this.OnAdd_DateChanging(value);
					this.SendPropertyChanging();
					this._Add_Date = value;
					this.SendPropertyChanged("Add_Date");
					this.OnAdd_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegonlineSuperAdmin", DbType="Bit")]
		public System.Nullable<bool> RegonlineSuperAdmin
		{
			get
			{
				return this._RegonlineSuperAdmin;
			}
			set
			{
				if ((this._RegonlineSuperAdmin != value))
				{
					this.OnRegonlineSuperAdminChanging(value);
					this.SendPropertyChanging();
					this._RegonlineSuperAdmin = value;
					this.SendPropertyChanged("RegonlineSuperAdmin");
					this.OnRegonlineSuperAdminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shortcuts")]
	public partial class Shortcut : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Description;
		
		private System.Nullable<int> _EventId;
		
		private System.Nullable<byte> _PageID;
		
		private string _CustomLink;
		
		private System.Nullable<bool> _nonCustomize;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnEventIdChanging(System.Nullable<int> value);
    partial void OnEventIdChanged();
    partial void OnPageIDChanging(System.Nullable<byte> value);
    partial void OnPageIDChanged();
    partial void OnCustomLinkChanging(string value);
    partial void OnCustomLinkChanged();
    partial void OnnonCustomizeChanging(System.Nullable<bool> value);
    partial void OnnonCustomizeChanged();
    #endregion
		
		public Shortcut()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventId", DbType="Int")]
		public System.Nullable<int> EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				if ((this._EventId != value))
				{
					this.OnEventIdChanging(value);
					this.SendPropertyChanging();
					this._EventId = value;
					this.SendPropertyChanged("EventId");
					this.OnEventIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageID", DbType="TinyInt")]
		public System.Nullable<byte> PageID
		{
			get
			{
				return this._PageID;
			}
			set
			{
				if ((this._PageID != value))
				{
					this.OnPageIDChanging(value);
					this.SendPropertyChanging();
					this._PageID = value;
					this.SendPropertyChanged("PageID");
					this.OnPageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomLink", DbType="NVarChar(1000)")]
		public string CustomLink
		{
			get
			{
				return this._CustomLink;
			}
			set
			{
				if ((this._CustomLink != value))
				{
					this.OnCustomLinkChanging(value);
					this.SendPropertyChanging();
					this._CustomLink = value;
					this.SendPropertyChanged("CustomLink");
					this.OnCustomLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nonCustomize", DbType="Bit")]
		public System.Nullable<bool> nonCustomize
		{
			get
			{
				return this._nonCustomize;
			}
			set
			{
				if ((this._nonCustomize != value))
				{
					this.OnnonCustomizeChanging(value);
					this.SendPropertyChanging();
					this._nonCustomize = value;
					this.SendPropertyChanged("nonCustomize");
					this.OnnonCustomizeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
