#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegOnline.RegressionTest.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ROWarehouse")]
	public partial class ROWarehouseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertInvoiceItems_AdHoc(InvoiceItems_AdHoc instance);
    partial void UpdateInvoiceItems_AdHoc(InvoiceItems_AdHoc instance);
    partial void DeleteInvoiceItems_AdHoc(InvoiceItems_AdHoc instance);
    partial void InsertALLDATE(ALLDATE instance);
    partial void UpdateALLDATE(ALLDATE instance);
    partial void DeleteALLDATE(ALLDATE instance);
    #endregion

		public ROWarehouseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ROWarehouseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ROWarehouseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ROWarehouseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<InvoiceItems_AdHoc> InvoiceItems_AdHocs
		{
			get
			{
				return this.GetTable<InvoiceItems_AdHoc>();
			}
		}
		
		public System.Data.Linq.Table<ALLDATE> ALLDATEs
		{
			get
			{
				return this.GetTable<ALLDATE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InvoiceItems_AdHoc")]
	public partial class InvoiceItems_AdHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CustomerId;
		
		private short _TypeId;
		
		private int _EventId;
		
		private System.DateTime _StartDate;
		
		private System.DateTime _EndDate;
		
		private System.Nullable<decimal> _CCAmount;
		
		private System.Nullable<decimal> _CCCost;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<int> _RegCount;
		
		private string _INVOICE_COMMENT;
		
		private string _DBNAME;
		
		private System.Nullable<bool> _isOrder;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerIdChanging(int value);
    partial void OnCustomerIdChanged();
    partial void OnTypeIdChanging(short value);
    partial void OnTypeIdChanged();
    partial void OnEventIdChanging(int value);
    partial void OnEventIdChanged();
    partial void OnStartDateChanging(System.DateTime value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.DateTime value);
    partial void OnEndDateChanged();
    partial void OnCCAmountChanging(System.Nullable<decimal> value);
    partial void OnCCAmountChanged();
    partial void OnCCCostChanging(System.Nullable<decimal> value);
    partial void OnCCCostChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OnRegCountChanging(System.Nullable<int> value);
    partial void OnRegCountChanged();
    partial void OnINVOICE_COMMENTChanging(string value);
    partial void OnINVOICE_COMMENTChanged();
    partial void OnDBNAMEChanging(string value);
    partial void OnDBNAMEChanged();
    partial void OnisOrderChanging(System.Nullable<bool> value);
    partial void OnisOrderChanged();
    #endregion
		
		public InvoiceItems_AdHoc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeId", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short TypeId
		{
			get
			{
				return this._TypeId;
			}
			set
			{
				if ((this._TypeId != value))
				{
					this.OnTypeIdChanging(value);
					this.SendPropertyChanging();
					this._TypeId = value;
					this.SendPropertyChanged("TypeId");
					this.OnTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				if ((this._EventId != value))
				{
					this.OnEventIdChanging(value);
					this.SendPropertyChanging();
					this._EventId = value;
					this.SendPropertyChanged("EventId");
					this.OnEventIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCAmount", DbType="Money")]
		public System.Nullable<decimal> CCAmount
		{
			get
			{
				return this._CCAmount;
			}
			set
			{
				if ((this._CCAmount != value))
				{
					this.OnCCAmountChanging(value);
					this.SendPropertyChanging();
					this._CCAmount = value;
					this.SendPropertyChanged("CCAmount");
					this.OnCCAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCost", DbType="Money")]
		public System.Nullable<decimal> CCCost
		{
			get
			{
				return this._CCCost;
			}
			set
			{
				if ((this._CCCost != value))
				{
					this.OnCCCostChanging(value);
					this.SendPropertyChanging();
					this._CCCost = value;
					this.SendPropertyChanged("CCCost");
					this.OnCCCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegCount", DbType="Int")]
		public System.Nullable<int> RegCount
		{
			get
			{
				return this._RegCount;
			}
			set
			{
				if ((this._RegCount != value))
				{
					this.OnRegCountChanging(value);
					this.SendPropertyChanging();
					this._RegCount = value;
					this.SendPropertyChanged("RegCount");
					this.OnRegCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INVOICE_COMMENT", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string INVOICE_COMMENT
		{
			get
			{
				return this._INVOICE_COMMENT;
			}
			set
			{
				if ((this._INVOICE_COMMENT != value))
				{
					this.OnINVOICE_COMMENTChanging(value);
					this.SendPropertyChanging();
					this._INVOICE_COMMENT = value;
					this.SendPropertyChanged("INVOICE_COMMENT");
					this.OnINVOICE_COMMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBNAME", DbType="VarChar(20)")]
		public string DBNAME
		{
			get
			{
				return this._DBNAME;
			}
			set
			{
				if ((this._DBNAME != value))
				{
					this.OnDBNAMEChanging(value);
					this.SendPropertyChanging();
					this._DBNAME = value;
					this.SendPropertyChanged("DBNAME");
					this.OnDBNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isOrder", DbType="Bit")]
		public System.Nullable<bool> isOrder
		{
			get
			{
				return this._isOrder;
			}
			set
			{
				if ((this._isOrder != value))
				{
					this.OnisOrderChanging(value);
					this.SendPropertyChanging();
					this._isOrder = value;
					this.SendPropertyChanged("isOrder");
					this.OnisOrderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ALLDATES")]
	public partial class ALLDATE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _DAYNOW;
		
		private byte _BUILDSTATUS;
		
		private System.Nullable<int> _ROWMONTH;
		
		private System.Nullable<int> _ROWYEAR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDAYNOWChanging(System.DateTime value);
    partial void OnDAYNOWChanged();
    partial void OnBUILDSTATUSChanging(byte value);
    partial void OnBUILDSTATUSChanged();
    partial void OnROWMONTHChanging(System.Nullable<int> value);
    partial void OnROWMONTHChanged();
    partial void OnROWYEARChanging(System.Nullable<int> value);
    partial void OnROWYEARChanged();
    #endregion
		
		public ALLDATE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAYNOW", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DAYNOW
		{
			get
			{
				return this._DAYNOW;
			}
			set
			{
				if ((this._DAYNOW != value))
				{
					this.OnDAYNOWChanging(value);
					this.SendPropertyChanging();
					this._DAYNOW = value;
					this.SendPropertyChanged("DAYNOW");
					this.OnDAYNOWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUILDSTATUS", DbType="TinyInt NOT NULL")]
		public byte BUILDSTATUS
		{
			get
			{
				return this._BUILDSTATUS;
			}
			set
			{
				if ((this._BUILDSTATUS != value))
				{
					this.OnBUILDSTATUSChanging(value);
					this.SendPropertyChanging();
					this._BUILDSTATUS = value;
					this.SendPropertyChanged("BUILDSTATUS");
					this.OnBUILDSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWMONTH", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ROWMONTH
		{
			get
			{
				return this._ROWMONTH;
			}
			set
			{
				if ((this._ROWMONTH != value))
				{
					this.OnROWMONTHChanging(value);
					this.SendPropertyChanging();
					this._ROWMONTH = value;
					this.SendPropertyChanged("ROWMONTH");
					this.OnROWMONTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWYEAR", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ROWYEAR
		{
			get
			{
				return this._ROWYEAR;
			}
			set
			{
				if ((this._ROWYEAR != value))
				{
					this.OnROWYEARChanging(value);
					this.SendPropertyChanging();
					this._ROWYEAR = value;
					this.SendPropertyChanged("ROWYEAR");
					this.OnROWYEARChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
