//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute("RegOnline.RegressionTestConfig", Namespace = "", IsNullable = false)]
public partial class RegOnlineRegressionTestConfig
{

    private RegOnlineRegressionTestConfigEnvironments environmentsField;

    private RegOnlineRegressionTestConfigWebService[] webServicesField;

    private RegOnlineRegressionTestConfigBrowsers browsersField;

    private int timeZoneDifferenceField;

    private RegOnlineRegressionTestConfigNUnitAddin nUnitAddinField;

    /// <remarks/>
    public RegOnlineRegressionTestConfigEnvironments Environments
    {
        get
        {
            return this.environmentsField;
        }
        set
        {
            this.environmentsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("WebService", IsNullable = false)]
    public RegOnlineRegressionTestConfigWebService[] WebServices
    {
        get
        {
            return this.webServicesField;
        }
        set
        {
            this.webServicesField = value;
        }
    }

    /// <remarks/>
    public RegOnlineRegressionTestConfigBrowsers Browsers
    {
        get
        {
            return this.browsersField;
        }
        set
        {
            this.browsersField = value;
        }
    }

    /// <remarks/>
    public int TimeZoneDifference
    {
        get
        {
            return this.timeZoneDifferenceField;
        }
        set
        {
            this.timeZoneDifferenceField = value;
        }
    }

    /// <remarks/>
    public RegOnlineRegressionTestConfigNUnitAddin NUnitAddin
    {
        get
        {
            return this.nUnitAddinField;
        }
        set
        {
            this.nUnitAddinField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RegOnlineRegressionTestConfigEnvironments
{

    private RegOnlineRegressionTestConfigEnvironmentsPreferred preferredField;

    private RegOnlineRegressionTestConfigEnvironmentsEnvironment[] environmentField;

    /// <remarks/>
    public RegOnlineRegressionTestConfigEnvironmentsPreferred Preferred
    {
        get
        {
            return this.preferredField;
        }
        set
        {
            this.preferredField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Environment")]
    public RegOnlineRegressionTestConfigEnvironmentsEnvironment[] Environment
    {
        get
        {
            return this.environmentField;
        }
        set
        {
            this.environmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RegOnlineRegressionTestConfigEnvironmentsPreferred
{

    private string environmentField;

    private string privateLabelField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Environment
    {
        get
        {
            return this.environmentField;
        }
        set
        {
            this.environmentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PrivateLabel
    {
        get
        {
            return this.privateLabelField;
        }
        set
        {
            this.privateLabelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RegOnlineRegressionTestConfigEnvironmentsEnvironment
{

    private RegOnlineRegressionTestConfigEnvironmentsEnvironmentAccount[] accountField;

    private string nameField;

    private string clientDbConnectionField;

    private string rOMasterConnectionField;

    private string rOWarehouseConnectionField;

    private string dataPathField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Account")]
    public RegOnlineRegressionTestConfigEnvironmentsEnvironmentAccount[] Account
    {
        get
        {
            return this.accountField;
        }
        set
        {
            this.accountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ClientDbConnection
    {
        get
        {
            return this.clientDbConnectionField;
        }
        set
        {
            this.clientDbConnectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ROMasterConnection
    {
        get
        {
            return this.rOMasterConnectionField;
        }
        set
        {
            this.rOMasterConnectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ROWarehouseConnection
    {
        get
        {
            return this.rOWarehouseConnectionField;
        }
        set
        {
            this.rOWarehouseConnectionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DataPath
    {
        get
        {
            return this.dataPathField;
        }
        set
        {
            this.dataPathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RegOnlineRegressionTestConfigEnvironmentsEnvironmentAccount
{

    private string domainNameField;

    private int idField;

    private string loginField;

    private string passwordField;

    private string folderField;

    private string xAuthVersionField;

    private string nameField;

    /// <remarks/>
    public string DomainName
    {
        get
        {
            return this.domainNameField;
        }
        set
        {
            this.domainNameField = value;
        }
    }

    /// <remarks/>
    public int Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    public string Login
    {
        get
        {
            return this.loginField;
        }
        set
        {
            this.loginField = value;
        }
    }

    /// <remarks/>
    public string Password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }

    /// <remarks/>
    public string Folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }

    /// <remarks/>
    public string XAuthVersion
    {
        get
        {
            return this.xAuthVersionField;
        }
        set
        {
            this.xAuthVersionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RegOnlineRegressionTestConfigWebService
{

    private string urlField;

    private string endpointConfigNameField;

    private string nameField;

    /// <remarks/>
    public string Url
    {
        get
        {
            return this.urlField;
        }
        set
        {
            this.urlField = value;
        }
    }

    /// <remarks/>
    public string EndpointConfigName
    {
        get
        {
            return this.endpointConfigNameField;
        }
        set
        {
            this.endpointConfigNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RegOnlineRegressionTestConfigBrowsers
{

    private string chromeDriverPathField;

    private RegOnlineRegressionTestConfigBrowsersBrowser[] browserField;

    private string currentField;

    /// <remarks/>
    public string ChromeDriverPath
    {
        get
        {
            return this.chromeDriverPathField;
        }
        set
        {
            this.chromeDriverPathField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Browser")]
    public RegOnlineRegressionTestConfigBrowsersBrowser[] Browser
    {
        get
        {
            return this.browserField;
        }
        set
        {
            this.browserField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Current
    {
        get
        {
            return this.currentField;
        }
        set
        {
            this.currentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RegOnlineRegressionTestConfigBrowsersBrowser
{

    private RegOnlineRegressionTestConfigBrowsersBrowserBinaryPath binaryPathField;

    private RegOnlineRegressionTestConfigBrowsersBrowserProfilePath profilePathField;

    private string nameField;

    /// <remarks/>
    public RegOnlineRegressionTestConfigBrowsersBrowserBinaryPath BinaryPath
    {
        get
        {
            return this.binaryPathField;
        }
        set
        {
            this.binaryPathField = value;
        }
    }

    /// <remarks/>
    public RegOnlineRegressionTestConfigBrowsersBrowserProfilePath ProfilePath
    {
        get
        {
            return this.profilePathField;
        }
        set
        {
            this.profilePathField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RegOnlineRegressionTestConfigBrowsersBrowserBinaryPath
{

    private bool enableField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Enable
    {
        get
        {
            return this.enableField;
        }
        set
        {
            this.enableField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RegOnlineRegressionTestConfigBrowsersBrowserProfilePath
{

    private bool enableField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Enable
    {
        get
        {
            return this.enableField;
        }
        set
        {
            this.enableField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RegOnlineRegressionTestConfigNUnitAddin
{

    private bool reportBackField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ReportBack
    {
        get
        {
            return this.reportBackField;
        }
        set
        {
            this.reportBackField = value;
        }
    }
}
