//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegOnline.RegressionTest.Fixtures.API.RegOnlineGetEventsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegOnlineGetEventsService.getEventsSoap")]
    public interface getEventsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ByAccountID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ByAccountID(int AccountID, string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ByAccountIDWithFilters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ByAccountIDWithFilters(int AccountID, string Username, string Password, string xmlFilterData, string FilterOperator, bool LikeMatching);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ByAccountIDEventID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ByAccountIDEventID(int AccountID, string Username, string Password, int EventId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface getEventsSoapChannel : RegOnline.RegressionTest.Fixtures.API.RegOnlineGetEventsService.getEventsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getEventsSoapClient : System.ServiceModel.ClientBase<RegOnline.RegressionTest.Fixtures.API.RegOnlineGetEventsService.getEventsSoap>, RegOnline.RegressionTest.Fixtures.API.RegOnlineGetEventsService.getEventsSoap {
        
        public getEventsSoapClient() {
        }
        
        public getEventsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public getEventsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public getEventsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public getEventsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ByAccountID(int AccountID, string Username, string Password) {
            return base.Channel.ByAccountID(AccountID, Username, Password);
        }
        
        public string ByAccountIDWithFilters(int AccountID, string Username, string Password, string xmlFilterData, string FilterOperator, bool LikeMatching) {
            return base.Channel.ByAccountIDWithFilters(AccountID, Username, Password, xmlFilterData, FilterOperator, LikeMatching);
        }
        
        public string ByAccountIDEventID(int AccountID, string Username, string Password, int EventId) {
            return base.Channel.ByAccountIDEventID(AccountID, Username, Password, EventId);
        }
    }
}
