//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegOnline.RegressionTest.Fixtures.API.RegOnlineMemberAuthService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.regonline.com/webservices/", ConfigurationName="RegOnlineMemberAuthService.memberAuthorizationSoap")]
    public interface memberAuthorizationSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.regonline.com/webservices/authorizeMember", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string authorizeMember(string customerUserName, string customerPassword, int eventID, string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.regonline.com/webservices/authorizeMemberWithEmailAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string authorizeMemberWithEmailAddress(string customerUserName, string customerPassword, int eventID, string emailAddress, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface memberAuthorizationSoapChannel : RegOnline.RegressionTest.Fixtures.API.RegOnlineMemberAuthService.memberAuthorizationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class memberAuthorizationSoapClient : System.ServiceModel.ClientBase<RegOnline.RegressionTest.Fixtures.API.RegOnlineMemberAuthService.memberAuthorizationSoap>, RegOnline.RegressionTest.Fixtures.API.RegOnlineMemberAuthService.memberAuthorizationSoap {
        
        public memberAuthorizationSoapClient() {
        }
        
        public memberAuthorizationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public memberAuthorizationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public memberAuthorizationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public memberAuthorizationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string authorizeMember(string customerUserName, string customerPassword, int eventID, string userName, string password) {
            return base.Channel.authorizeMember(customerUserName, customerPassword, eventID, userName, password);
        }
        
        public string authorizeMemberWithEmailAddress(string customerUserName, string customerPassword, int eventID, string emailAddress, string password) {
            return base.Channel.authorizeMemberWithEmailAddress(customerUserName, customerPassword, eventID, emailAddress, password);
        }
    }
}
