//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegOnline.RegressionTest.Fixtures.API.RegOnlineRegTrackerService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegOnlineRegTrackerService.WSRegBugSoap")]
    public interface WSRegBugSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Validate(int AccountId, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServerDateTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime GetServerDateTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserForms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserForms(int AccountId, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserFormsStatistics", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserFormsStatistics(int AccountId, string EventIds, System.DateTime LastUpdateDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateWebSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateWebSession(int AccountId, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoginUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetLoginUrl(bool DirectAccess, int AccountId, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSnapshotReportUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSnapshotReportUrl(bool DirectAccess, int EventID, int AccountId, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttendeeReportUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAttendeeReportUrl(bool DirectAccess, int EventID, int AccountId, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttendeeReportUrlWithDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAttendeeReportUrlWithDate(bool DirectAccess, int EventID, System.DateTime DateFilter, int AccountId, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHelpUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHelpUrl();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSRegBugSoapChannel : RegOnline.RegressionTest.Fixtures.API.RegOnlineRegTrackerService.WSRegBugSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSRegBugSoapClient : System.ServiceModel.ClientBase<RegOnline.RegressionTest.Fixtures.API.RegOnlineRegTrackerService.WSRegBugSoap>, RegOnline.RegressionTest.Fixtures.API.RegOnlineRegTrackerService.WSRegBugSoap {
        
        public WSRegBugSoapClient() {
        }
        
        public WSRegBugSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSRegBugSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSRegBugSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSRegBugSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Validate(int AccountId, string username, string password) {
            return base.Channel.Validate(AccountId, username, password);
        }
        
        public System.DateTime GetServerDateTime() {
            return base.Channel.GetServerDateTime();
        }
        
        public System.Data.DataSet GetUserForms(int AccountId, string username, string password) {
            return base.Channel.GetUserForms(AccountId, username, password);
        }
        
        public System.Data.DataSet GetUserFormsStatistics(int AccountId, string EventIds, System.DateTime LastUpdateDate) {
            return base.Channel.GetUserFormsStatistics(AccountId, EventIds, LastUpdateDate);
        }
        
        public string CreateWebSession(int AccountId, string username, string password) {
            return base.Channel.CreateWebSession(AccountId, username, password);
        }
        
        public string GetLoginUrl(bool DirectAccess, int AccountId, string username, string password) {
            return base.Channel.GetLoginUrl(DirectAccess, AccountId, username, password);
        }
        
        public string GetSnapshotReportUrl(bool DirectAccess, int EventID, int AccountId, string username, string password) {
            return base.Channel.GetSnapshotReportUrl(DirectAccess, EventID, AccountId, username, password);
        }
        
        public string GetAttendeeReportUrl(bool DirectAccess, int EventID, int AccountId, string username, string password) {
            return base.Channel.GetAttendeeReportUrl(DirectAccess, EventID, AccountId, username, password);
        }
        
        public string GetAttendeeReportUrlWithDate(bool DirectAccess, int EventID, System.DateTime DateFilter, int AccountId, string username, string password) {
            return base.Channel.GetAttendeeReportUrlWithDate(DirectAccess, EventID, DateFilter, AccountId, username, password);
        }
        
        public string GetHelpUrl() {
            return base.Channel.GetHelpUrl();
        }
    }
}
