//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegOnline.RegressionTest.Fixtures.API.RegOnlineXmlUpdaterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegOnlineXmlUpdaterService.XmlUpdaterSoap")]
    public interface XmlUpdaterSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRegistrations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateRegistrations(string login, string password, int eventID, string xmlData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XmlUpdaterSoapChannel : RegOnline.RegressionTest.Fixtures.API.RegOnlineXmlUpdaterService.XmlUpdaterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XmlUpdaterSoapClient : System.ServiceModel.ClientBase<RegOnline.RegressionTest.Fixtures.API.RegOnlineXmlUpdaterService.XmlUpdaterSoap>, RegOnline.RegressionTest.Fixtures.API.RegOnlineXmlUpdaterService.XmlUpdaterSoap {
        
        public XmlUpdaterSoapClient() {
        }
        
        public XmlUpdaterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XmlUpdaterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlUpdaterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlUpdaterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string UpdateRegistrations(string login, string password, int eventID, string xmlData) {
            return base.Channel.UpdateRegistrations(login, password, eventID, xmlData);
        }
    }
}
