//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.regonline.com/webservices/2007/08/RegistrationUpdateService", ConfigurationName="RegOnlineRegUpdateService.RegistrationUpdateServiceSoap")]
    public interface RegistrationUpdateServiceSoap {
        
        // CODEGEN: Generating message contract since the operation UpdateRegistrations is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.regonline.com/webservices/2007/08/RegistrationUpdateService/UpdateRegi" +
            "strations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.UpdateRegistrationsResponse1 UpdateRegistrations(RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.UpdateRegistrationsRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.regonline.com/webservices/2007/08/RegistrationUpdateService")]
    public partial class updateRegistrationsRequestHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.regonline.com/webservices/2007/08/RegistrationUpdateServiceTypes")]
    public partial class updateRegistrationsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string updateRegistrationsResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string updateRegistrationsResult {
            get {
                return this.updateRegistrationsResultField;
            }
            set {
                this.updateRegistrationsResultField = value;
                this.RaisePropertyChanged("updateRegistrationsResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.regonline.com/webservices/2007/08/RegistrationUpdateServiceTypes")]
    public partial class nameValueQuantitySet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldNameField;
        
        private string valueField;
        
        private int quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
                this.RaisePropertyChanged("fieldName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.regonline.com/webservices/2007/08/RegistrationUpdateServiceTypes")]
    public partial class registrationData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int registrationIdField;
        
        private nameValueQuantitySet[] feesField;
        
        private nameValueQuantitySet[] agendaItemsField;
        
        private nameValueQuantitySet[] customFieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int registrationId {
            get {
                return this.registrationIdField;
            }
            set {
                this.registrationIdField = value;
                this.RaisePropertyChanged("registrationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("fee", IsNullable=false)]
        public nameValueQuantitySet[] fees {
            get {
                return this.feesField;
            }
            set {
                this.feesField = value;
                this.RaisePropertyChanged("fees");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("agendaItem", IsNullable=false)]
        public nameValueQuantitySet[] agendaItems {
            get {
                return this.agendaItemsField;
            }
            set {
                this.agendaItemsField = value;
                this.RaisePropertyChanged("agendaItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("customField", IsNullable=false)]
        public nameValueQuantitySet[] customFields {
            get {
                return this.customFieldsField;
            }
            set {
                this.customFieldsField = value;
                this.RaisePropertyChanged("customFields");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.regonline.com/webservices/2007/08/RegistrationUpdateServiceTypes")]
    public partial class updateRegistrationsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int eventIDField;
        
        private registrationData[] registrationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int eventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
                this.RaisePropertyChanged("eventID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("registration", IsNullable=false)]
        public registrationData[] registrations {
            get {
                return this.registrationsField;
            }
            set {
                this.registrationsField = value;
                this.RaisePropertyChanged("registrations");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRegistrationsRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.regonline.com/webservices/2007/08/RegistrationUpdateService")]
        public RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.updateRegistrationsRequestHeader updateRegistrationsRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.regonline.com/webservices/2007/08/RegistrationUpdateService", Order=0)]
        public RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.updateRegistrationsRequest UpdateRegistrationsRequest;
        
        public UpdateRegistrationsRequest1() {
        }
        
        public UpdateRegistrationsRequest1(RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.updateRegistrationsRequestHeader updateRegistrationsRequestHeader, RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.updateRegistrationsRequest UpdateRegistrationsRequest) {
            this.updateRegistrationsRequestHeader = updateRegistrationsRequestHeader;
            this.UpdateRegistrationsRequest = UpdateRegistrationsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRegistrationsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.regonline.com/webservices/2007/08/RegistrationUpdateService", Order=0)]
        public RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.updateRegistrationsResponse UpdateRegistrationsResponse;
        
        public UpdateRegistrationsResponse1() {
        }
        
        public UpdateRegistrationsResponse1(RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.updateRegistrationsResponse UpdateRegistrationsResponse) {
            this.UpdateRegistrationsResponse = UpdateRegistrationsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistrationUpdateServiceSoapChannel : RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.RegistrationUpdateServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationUpdateServiceSoapClient : System.ServiceModel.ClientBase<RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.RegistrationUpdateServiceSoap>, RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.RegistrationUpdateServiceSoap {
        
        public RegistrationUpdateServiceSoapClient() {
        }
        
        public RegistrationUpdateServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationUpdateServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationUpdateServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationUpdateServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.UpdateRegistrationsResponse1 RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.RegistrationUpdateServiceSoap.UpdateRegistrations(RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.UpdateRegistrationsRequest1 request) {
            return base.Channel.UpdateRegistrations(request);
        }
        
        public RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.updateRegistrationsResponse UpdateRegistrations(RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.updateRegistrationsRequestHeader updateRegistrationsRequestHeader, RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.updateRegistrationsRequest UpdateRegistrationsRequest) {
            RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.UpdateRegistrationsRequest1 inValue = new RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.UpdateRegistrationsRequest1();
            inValue.updateRegistrationsRequestHeader = updateRegistrationsRequestHeader;
            inValue.UpdateRegistrationsRequest = UpdateRegistrationsRequest;
            RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.UpdateRegistrationsResponse1 retVal = ((RegOnline.RegressionTest.Fixtures.API.RegOnlineRegUpdateService.RegistrationUpdateServiceSoap)(this)).UpdateRegistrations(inValue);
            return retVal.UpdateRegistrationsResponse;
        }
    }
}
